import axios from 'axios';
import React, { useState, useEffect } from 'react';

import Hero from './components/Hero';
import World from './components/World';

function App() {
	// const [worlds, setWorlds] = useState({
	// 	"WC38": {
	// 		"firstSeen": 1713062705563,
	// 		"players": [
	// 			"Coolkid1206",
	// 			"RevolvingOcelot",
	// 			"Simpmulation",
	// 			"ZipperDeer",
	// 			"Vulpix1",
	// 			"ReisBlau",
	// 			"danot",
	// 			"KodaAndKeyno",
	// 			"hunter2776",
	// 			"Stunbud",
	// 			"InkedSk8ter",
	// 			"nChaine",
	// 			"MrQBurt",
	// 			"TFoxy13",
	// 			"TheLordXerxes",
	// 			"takayama_bros",
	// 			"FelixTape",
	// 			"yotaaaaa",
	// 			"Humongoustea178",
	// 			"Drawss",
	// 			"Bas_Tech",
	// 			"tararaco",
	// 			"FluffyPixel9",
	// 			"Fanxiang",
	// 			"JustJeffery",
	// 			"Ed3l",
	// 			"swimwater",
	// 			"LionKing421",
	// 			"Lemonsan666",
	// 			"0MNlV0RE",
	// 			"Syfilen"
	// 		]
	// 	},
	// 	"WC43": {
	// 		"firstSeen": 1713061711279,
	// 		"players": [
	// 			"Gamerboy1322020",
	// 			"DuskyDusky",
	// 			"KMsan",
	// 			"Crimsondevilsin",
	// 			"catg1rl",
	// 			"Luna__Prism",
	// 			"Henry_814",
	// 			"ThatFortniteGuy",
	// 			"Oldfox39",
	// 			"PKfreeze123",
	// 			"readly44",
	// 			"SaffronCSF",
	// 			"N0tChris",
	// 			"dizaster6th",
	// 			"Its_Meh",
	// 			"Chambers02",
	// 			"diamond_slayer5",
	// 			"Prowombat3",
	// 			"TheBryard",
	// 			"brqndonn",
	// 			"punscake",
	// 			"Frozzx3102",
	// 			"NokaHoa",
	// 			"StayALIV3",
	// 			"hoMiroNg",
	// 			"Woealer",
	// 			"Cruuk",
	// 			"cluster_amarylli",
	// 			"CrescentedFish",
	// 			"IcarusDies",
	// 			"Lucid_Hope",
	// 			"muzf"
	// 		]
	// 	},
	// 	"WC42": {
	// 		"firstSeen": 1713063076995,
	// 		"players": [
	// 			"cerealki11ing",
	// 			"koiifish_",
	// 			"sharpieaddictt",
	// 			"goombas_killer",
	// 			"Le_Patito",
	// 			"lopro2010",
	// 			"XXMVNM123",
	// 			"Meniscussssss",
	// 			"Griimmmm",
	// 			"ScytheOfLife",
	// 			"Artificed",
	// 			"_Commander_Ike_",
	// 			"theSparkalina",
	// 			"pugman421",
	// 			"BoyofLength",
	// 			"cam06060",
	// 			"Debauche",
	// 			"brilliantknight",
	// 			"Princ3Victor",
	// 			"Solublee",
	// 			"yoshro27",
	// 			"gobert_rl",
	// 			"FireBlux3",
	// 			"azhuuk",
	// 			"TastyJason",
	// 			"Taiwan_is_first",
	// 			"monkeysorcerer2",
	// 			"yayo2016",
	// 			"FluffyCape87348",
	// 			"13Amicus",
	// 			"Lrum"
	// 		]
	// 	},
	// 	"WC10": {
	// 		"firstSeen": 1713046407836,
	// 		"players": [
	// 			"migu31",
	// 			"Rd_Ctrlr",
	// 			"ZaiSama_",
	// 			"JimbiFist",
	// 			"isakax",
	// 			"_sni7ch",
	// 			"MaxTm8",
	// 			"ThDestr",
	// 			"Peytondude8",
	// 			"Doge4517",
	// 			"zMars",
	// 			"ningbun",
	// 			"mosquitokill",
	// 			"Aggusteen",
	// 			"RipleyTheAxolotl",
	// 			"nerdynerdz",
	// 			"Lastly",
	// 			"Cajahope",
	// 			"MasterKaboom",
	// 			"UnluckyPill",
	// 			"Necryo_",
	// 			"dollbite",
	// 			"UnVanilla",
	// 			"aqua0763",
	// 			"EchoingGryffin",
	// 			"xTheRedx",
	// 			"jorge_ivan123",
	// 			"vasectomylover2",
	// 			"BakaUnicorn14",
	// 			"IsseiHDxD",
	// 			"Thira8",
	// 			"_Toos_",
	// 			"oseyuki",
	// 			"Orphion_"
	// 		]
	// 	},
	// 	"WC1": {
	// 		"firstSeen": 1713041989209,
	// 		"players": [
	// 			"kitsunyaaaa",
	// 			"igambleinchat",
	// 			"Pokiie",
	// 			"PIXEL_POSTER",
	// 			"MrJulianB0T",
	// 			"oKlaws_",
	// 			"Aovhii",
	// 			"ablockofdort",
	// 			"Owieczka15",
	// 			"OppositeMirror",
	// 			"Error_402",
	// 			"Aureuix",
	// 			"5ura",
	// 			"PlasmaWarrior",
	// 			"PaisleyBiscuit",
	// 			"TrNyxo",
	// 			"BatClub",
	// 			"leonatcam",
	// 			"MCPro_Gamer",
	// 			"Irredescent",
	// 			"Forever_Night1",
	// 			"IFionnaI_",
	// 			"beurfus",
	// 			"Manoogi",
	// 			"2000IQ",
	// 			"NeverForgetten",
	// 			"Fishbasket74",
	// 			"JldwL",
	// 			"wilsan3",
	// 			"jacobwfvp1",
	// 			"G0ldenR0uoxls"
	// 		]
	// 	},
	// 	"WC17": {
	// 		"firstSeen": 1713048430984,
	// 		"players": [
	// 			11721172,
	// 			"LordGonner",
	// 			"Dorian_Marwood",
	// 			"_B3N450_",
	// 			"OmegaInbound",
	// 			"nickbraves1",
	// 			"twining_t86",
	// 			"WoodHolland",
	// 			"NasaNerd314",
	// 			"AkuroR7",
	// 			"DT_TKmVN",
	// 			"DT_Gura",
	// 			"Keqqu",
	// 			"WoodKast",
	// 			"DestroyManIV",
	// 			"vrodih",
	// 			"WoodVA",
	// 			"ThaWood",
	// 			"Incarceon_",
	// 			"WoodLost",
	// 			"Gombreng",
	// 			"WoodCreature",
	// 			"Jopher11733",
	// 			"SrReikuz",
	// 			"OmTaoEinsofManus",
	// 			"LaDvdCorzo",
	// 			"DT_Jack",
	// 			"WoodXP",
	// 			"PingouinDLS",
	// 			"SentryPickle",
	// 			"Voidarcher72",
	// 			"Cucho2910"
	// 		]
	// 	},
	// 	"WC27": {
	// 		"firstSeen": 1713059876644,
	// 		"players": [
	// 			"DanOldMan",
	// 			"Nomadixc",
	// 			"succbucket",
	// 			"meltingiam",
	// 			"ReeceReineke",
	// 			"Rade_emear",
	// 			"VetroFPS",
	// 			"FlowerPrincess",
	// 			"GerberaSymphony",
	// 			"Patro633",
	// 			"ScalesInSweaters",
	// 			"KN1GHTFALL",
	// 			"white_boy",
	// 			"CosmobbleSys",
	// 			"RAYAXY",
	// 			"oHate",
	// 			"VolkyPolky",
	// 			"BlakeDwarf",
	// 			"Nnama",
	// 			"IsaacDelta",
	// 			"FoxShr00m",
	// 			"feiPC123",
	// 			"Drbiznes",
	// 			"Baj_Baj",
	// 			"HiSlIgHt_",
	// 			"kristyboo",
	// 			"meemmeem1",
	// 			"oGeoff",
	// 			"icehawk54",
	// 			"Montews"
	// 		]
	// 	},
	// 	"WC36": {
	// 		"firstSeen": 1713030334852,
	// 		"players": [
	// 			"Yoonami",
	// 			"FireRex206966",
	// 			"Bosukude4649",
	// 			"Xzazel",
	// 			"Ewen_Le_Nain",
	// 			"egg4059",
	// 			"Nines_Own_Goal",
	// 			"WhiteNoise0113",
	// 			"EririLovegold",
	// 			"H4iKiri",
	// 			"HaNdY__",
	// 			"YufanC",
	// 			"itsdannyright"
	// 		]
	// 	},
	// 	"WC21": {
	// 		"firstSeen": 1713050547196,
	// 		"players": [
	// 			"LeLazi",
	// 			"Masojia_jp",
	// 			"Mihaukse",
	// 			"facelessgoat11",
	// 			"Dwaam",
	// 			"heiru6199",
	// 			"FluffySeal2988",
	// 			"PengosPongos",
	// 			"Univerouse",
	// 			"ihyukai",
	// 			"UhSnap",
	// 			"lil_headass",
	// 			"C4MERONXOX",
	// 			"_topaz",
	// 			"Spenchilada",
	// 			"Enick",
	// 			"DanOninho_",
	// 			"PerUnknown",
	// 			"Calluum",
	// 			"aDri9101",
	// 			"NKiritoN",
	// 			"King__Bob",
	// 			"IEA1000",
	// 			"Ethos999",
	// 			"adri88g",
	// 			"CatPlayingGames",
	// 			"BluBlueJay"
	// 		]
	// 	},
	// 	"WC28": {
	// 		"firstSeen": 1713037547549,
	// 		"players": [
	// 			"ObxM",
	// 			"Temtem_TS",
	// 			"Sumaho1008",
	// 			"DragxD",
	// 			"BuffJadeMining",
	// 			"Toasty_boi",
	// 			"Eshreal",
	// 			"Stil_",
	// 			"pugacy",
	// 			"Ruekimou",
	// 			"NotsoDumb",
	// 			"SP1_Dragon",
	// 			"Whath",
	// 			"Doggc",
	// 			"Cal_and_Ben",
	// 			"GooseCore",
	// 			"Sand_V3",
	// 			"TKW256",
	// 			"xSuzu",
	// 			"SilverlyNight",
	// 			"_Thinking_Face_",
	// 			"Blademaster0",
	// 			"Jasonplayzz",
	// 			"TheNelston",
	// 			"kubawu_",
	// 			"Oblong_Sushi",
	// 			"allizhi"
	// 		]
	// 	},
	// 	"WC18": {
	// 		"firstSeen": 1713052317725,
	// 		"players": [
	// 			"IDontLikeToDie",
	// 			"Shebn",
	// 			"VaadVaati",
	// 			"CitraSama",
	// 			"Scarlet_to_dream",
	// 			"YouAreRexist",
	// 			"badsoup",
	// 			"jaxonishere",
	// 			"Son_Of_Walter",
	// 			"minebrine10",
	// 			"GudSpeling",
	// 			"Black_Scorpion_",
	// 			"Colinix",
	// 			"Conan0LM",
	// 			"angycathy",
	// 			"yhtacygna",
	// 			"crafttatsuya",
	// 			"RanaKikker",
	// 			"xyrily",
	// 			"SleepyMistix",
	// 			"fangtianxing",
	// 			"Wynderia",
	// 			"Zatch",
	// 			"HRJDragon",
	// 			"Felirya"
	// 		]
	// 	},
	// 	"WC20": {
	// 		"firstSeen": 1713045226538,
	// 		"players": [
	// 			"Super_Sharkie",
	// 			"Mxxrm",
	// 			"maikeru34",
	// 			"lecie4",
	// 			"KeyWe_87_island",
	// 			"svinerus",
	// 			"GaboMcGamer",
	// 			"noateto1",
	// 			"Jenica",
	// 			"JessicaPink703",
	// 			"AdmiralDaizin",
	// 			"HimesakaLuna",
	// 			"XeiroFlora",
	// 			"Vzax",
	// 			"jaygoddd",
	// 			"Act1vateWindows",
	// 			"takasin1",
	// 			"NinjaChicken95",
	// 			"FancyKiwi",
	// 			"PartlySunny",
	// 			"Gensubaru",
	// 			"boyfrom",
	// 			"mikeworld3",
	// 			"R_Ruffles",
	// 			"TinyRedRaceCar",
	// 			"Oyasai_JE9100"
	// 		]
	// 	},
	// 	"WC9": {
	// 		"firstSeen": 1713037080442,
	// 		"players": [
	// 			"OrphanedChild",
	// 			"PimpleDimps",
	// 			"RTrinh563",
	// 			"Ahuizotll",
	// 			"RikuMochi",
	// 			"Qu3st1on",
	// 			"Ossydeussy",
	// 			"t4be",
	// 			"xXZaBriNgAXx",
	// 			"zJury",
	// 			"Cursed2w1",
	// 			"Paradision",
	// 			"sc2sr",
	// 			"Housery",
	// 			"RubMyMineshaft",
	// 			"p_b_d_matcha8931",
	// 			"DarkFeather556",
	// 			"xAkumi",
	// 			"SillyScrew",
	// 			"Azomth",
	// 			"yap_per",
	// 			"jia_qin",
	// 			"dog_eggs",
	// 			"Lemon_Pan",
	// 			"Mail_Watdaimod",
	// 			"FabDoesStuff",
	// 			"Nightslasher38",
	// 			"kyeun",
	// 			"AXYEHHOKPYTO",
	// 			"whiteguy48"
	// 		]
	// 	},
	// 	"WC37": {
	// 		"firstSeen": 1713050861666,
	// 		"players": [
	// 			"tummblez99",
	// 			"smaching",
	// 			"Frogstand",
	// 			"Techno_Guy_KWP",
	// 			"Ruinc",
	// 			"OverlordAlastor",
	// 			"SkimBeebs",
	// 			"WhiteFang__",
	// 			"YOKOKUMA",
	// 			"HeavyMetalHaven",
	// 			"TacoCat7653",
	// 			"ohitslemon",
	// 			"TakiCesar",
	// 			"BaggierTree3320",
	// 			"WestCandle_JP",
	// 			"wrubiix",
	// 			"Johnadam211212",
	// 			"Sub__Par",
	// 			"kai_chen0602",
	// 			"Zaidob",
	// 			"UnusualHeron",
	// 			"Fan2mario64",
	// 			"BarGam1",
	// 			"ryktcompassrose",
	// 			"MaybeLatah",
	// 			"TuLouis",
	// 			"Puurpleman",
	// 			"ElohmroW",
	// 			"Cataath"
	// 		]
	// 	},
	// 	"WC33": {
	// 		"firstSeen": 1713036613770,
	// 		"players": [
	// 			"TheZe_",
	// 			"IMagister",
	// 			"The_Big_Bunga",
	// 			"Mouseydavid10",
	// 			"Tqkened",
	// 			"LT_Universe",
	// 			"thatFishStick",
	// 			"ESTTGD",
	// 			"TheCloakMan",
	// 			"xx_bacon_man_xx",
	// 			"Rojeel",
	// 			"Iware_Pond",
	// 			"POPOPIYA",
	// 			"Mo1G4mez",
	// 			"Overvolt1000",
	// 			"SorrowfulLady",
	// 			"Skorm_Axebreaker",
	// 			"AWildHoshiyomi",
	// 			"mahiro1219",
	// 			"ProjectForceV2",
	// 			"rynf",
	// 			"ManMysterious",
	// 			"Brutakah",
	// 			"Red_Fox_Rogue",
	// 			"Crescentmoon621",
	// 			"falconthunder"
	// 		]
	// 	},
	// 	"WC14": {
	// 		"firstSeen": 1713059380165,
	// 		"players": [
	// 			"zeky",
	// 			"NOOBYPANDA_",
	// 			"Rahvin2007",
	// 			"Acorn11",
	// 			"Seraphim_Rayn",
	// 			"EpicWynn",
	// 			"Scarface_Connor",
	// 			"Ehsbii",
	// 			"Ulitiminer4172",
	// 			"xRisePunch",
	// 			"ekozi",
	// 			"MidNightMisT880",
	// 			"Nitroxlz",
	// 			"Ratalistic",
	// 			"Player6650",
	// 			"SnowFox166",
	// 			"EXARTIUS",
	// 			"aronkodol",
	// 			"Harm7",
	// 			"FraekInMuscle",
	// 			"Opmusic",
	// 			"thefugitiveminer",
	// 			"skyblueswordsman",
	// 			"TaKarir",
	// 			"nctrequiem",
	// 			"__Tempestissimo",
	// 			"RolleBolle55",
	// 			"ParasiticHelmint",
	// 			"Ventari_Wylde",
	// 			"pockt"
	// 		]
	// 	},
	// 	"WC35": {
	// 		"firstSeen": 1713050607784,
	// 		"players": [
	// 			"FaintCalf59547",
	// 			"DannyDanBoy",
	// 			"MERO_02",
	// 			"Blazedancer",
	// 			"illuminus_metam",
	// 			"sol798",
	// 			"Awkweat",
	// 			"SimplySlim3",
	// 			"Doctor_Whooves42",
	// 			"Jagaro",
	// 			"Gravetide",
	// 			"AnAceSpade",
	// 			"KREJ10",
	// 			"__bone__",
	// 			"cobalt771",
	// 			"jade_rabbit1124",
	// 			"Re0_Rem",
	// 			"ItsLionknight",
	// 			"0O0X0O0",
	// 			"McHimbo",
	// 			"PK2006",
	// 			"SassyGay",
	// 			"SueDillon",
	// 			"Chanwhun",
	// 			"KaoDremora",
	// 			"Smellbo_",
	// 			"Nightfury13",
	// 			"Jacobi102030",
	// 			"Greenbracelet",
	// 			"Volcanic_Gamer",
	// 			"Domisboss2014"
	// 		]
	// 	},
	// 	"WC15": {
	// 		"firstSeen": 1713041863547,
	// 		"players": [
	// 			"CaptainG2280",
	// 			"InozaAki_",
	// 			"Axyrius",
	// 			"Rita_87_island",
	// 			"SuperSein",
	// 			"Kneem",
	// 			"bluemidsdog",
	// 			"ABlack4",
	// 			"AtrejuPlays",
	// 			"driacore",
	// 			"dDANTE_S",
	// 			"Fleega",
	// 			"AreFeetShoes",
	// 			"TrissyTiger",
	// 			"Ataraxyia",
	// 			"KutekutoBonsai",
	// 			"LilacMasquerade",
	// 			"Arcellis",
	// 			"Marstrosity",
	// 			"TheMelonDragon",
	// 			"ILikeU",
	// 			"Murdery",
	// 			"PhyzzyBop",
	// 			"CrazyTiger12908",
	// 			"sbellebound",
	// 			"Mrblaze1301",
	// 			"uruy"
	// 		]
	// 	},
	// 	"WC12": {
	// 		"firstSeen": 1713057949533,
	// 		"players": [
	// 			"Fanta_lemonPie",
	// 			"Lord_Qwerty_Pyro",
	// 			"AlistorTheWolf",
	// 			"SpaceHusky17",
	// 			"Dragon_slayer820",
	// 			"sadgeleaf1",
	// 			"Starsxul",
	// 			"freeMCsmoke",
	// 			"zman1der",
	// 			"Chaioth_haQadesh",
	// 			"killaang",
	// 			"Vakama",
	// 			"danscorruption",
	// 			"x3n1",
	// 			"juli793",
	// 			"Jamal_meow",
	// 			"SPAC3M0NK3Y",
	// 			"Nekk0mancer",
	// 			"2Hero",
	// 			"wabey",
	// 			"chickrame",
	// 			"Drobicus",
	// 			"MortalMaximus",
	// 			"egyog",
	// 			"tsumikijenga_234",
	// 			"ChampionFighter",
	// 			"Clezynemy123",
	// 			"Dinhsiudeptrai",
	// 			"Tacosoftware9000",
	// 			"SinanBruh",
	// 			"Drawwy"
	// 		]
	// 	},
	// 	"WC22": {
	// 		"firstSeen": 1713037953076,
	// 		"players": [
	// 			"Blankown",
	// 			"vrdr",
	// 			"Legolucas1472",
	// 			"Fern_Ottors",
	// 			"Testo_",
	// 			"orangetofu",
	// 			"Stavrozius7",
	// 			"Lituk",
	// 			"TheAnonymousRain",
	// 			"daiebi14",
	// 			"defnotlexi",
	// 			"RazzorHDD",
	// 			"origamiking152",
	// 			"Jaggster",
	// 			"Weedow_",
	// 			"AutisticCrumbs",
	// 			"Rye21",
	// 			"sumituba4328",
	// 			"JammiestDodger",
	// 			"HX7D",
	// 			"Docokarra",
	// 			"oiSnow",
	// 			"FuturePlantsTM",
	// 			"Styx_He1ix",
	// 			"IgnisDragon",
	// 			"star473",
	// 			"ToucanTimm",
	// 			"omamesinzu",
	// 			"IIlShadowII",
	// 			"ItsJustKnoxx",
	// 			"Charlieoffps",
	// 			"catgirlviona",
	// 			"Dorothy62",
	// 			"Zerindal"
	// 		]
	// 	},
	// 	"WC34": {
	// 		"firstSeen": 1713042176818,
	// 		"players": [
	// 			"AndDrew_",
	// 			"latryxx",
	// 			"Duks",
	// 			"Trodeno",
	// 			"StealyOats",
	// 			"GooseTen",
	// 			"Capt_Fox241",
	// 			"VoraOfficial",
	// 			"Auri_El",
	// 			"Hyacinth_Oppop",
	// 			"GameHappy",
	// 			"IDoBeSimpingTho",
	// 			"odeska",
	// 			"Reser2207",
	// 			"bare__",
	// 			"TheEaf",
	// 			"FrostOffSum",
	// 			"GluePowa",
	// 			"Secret_FruityCat",
	// 			"BreadBurglar",
	// 			"inari080",
	// 			"kn8900",
	// 			"Poo_najak",
	// 			"PaLiNoxSR",
	// 			"CebuPacific",
	// 			"RaccoonLover9000",
	// 			"Monamiii",
	// 			"Run_O101",
	// 			"redpanda508"
	// 		]
	// 	},
	// 	"WC3": {
	// 		"firstSeen": 1713034563344,
	// 		"players": [
	// 			"Katalyst_x",
	// 			"Mirvam",
	// 			"Uoog",
	// 			"YerMumsDad",
	// 			"CrystalFlux",
	// 			"funkylezzo",
	// 			"SaibaKurokawa",
	// 			"AsianCat",
	// 			"gig4c4zo",
	// 			"Strife_Cloud",
	// 			"Forgetfulpass",
	// 			"Creampuffboy",
	// 			"MrGalacto",
	// 			"Daimax_19",
	// 			"Nooten_56",
	// 			"Mickaelhz",
	// 			"MoonAvem",
	// 			"thenumberonedud",
	// 			"Demonwes123",
	// 			"bobarken",
	// 			"Odogo",
	// 			"Wasasi",
	// 			"ixiclestinger22",
	// 			"MicrosRevenge",
	// 			"Hexodus",
	// 			"Damakos3"
	// 		]
	// 	},
	// 	"WC4": {
	// 		"firstSeen": 1713055616365,
	// 		"players": [
	// 			"ukcat68",
	// 			"MetalBox47",
	// 			"Flydane",
	// 			"morest",
	// 			"tonyloco13",
	// 			"JVRQ",
	// 			"rinobo1122",
	// 			"Super02starL",
	// 			"atomilogical",
	// 			"pnoot",
	// 			"Heidychyyy",
	// 			"MysticDireWolves",
	// 			"ItsLeafeon55",
	// 			"TheLukinator2022",
	// 			"KatskaBee",
	// 			"SarahLeSimp",
	// 			"FrootyToots",
	// 			"Xiissue",
	// 			"Gurdus",
	// 			"Doubletime_T",
	// 			"BliTZed_PaNdA",
	// 			"Mr_poopybutthole",
	// 			"Sir_Aaronymus",
	// 			"4nei",
	// 			"SleepyT2883",
	// 			"eatwithspork",
	// 			"MR_catalot",
	// 			"ImagineKami",
	// 			"helow127",
	// 			"Insighted",
	// 			"Sosit4",
	// 			"NinjaWasser",
	// 			"IamTheDuke"
	// 		]
	// 	},
	// 	"WC11": {
	// 		"firstSeen": 1713043607682,
	// 		"players": [
	// 			"Bennykelli1",
	// 			"Tis_awesomeness",
	// 			"SnUg3d",
	// 			"Wemydastore",
	// 			"GoodmanPasta",
	// 			"Whom_Asked",
	// 			"InfernalIE",
	// 			"derpsir",
	// 			"StreekSeyt",
	// 			"fj70",
	// 			"RamSimp",
	// 			"KSR2020",
	// 			"xXPoppa_WoodyXx",
	// 			"Dat808Taco",
	// 			"_Karsalesman_",
	// 			"Keldorn",
	// 			"bapafish",
	// 			"Tavahn",
	// 			"Pokeguy946",
	// 			"Beetown",
	// 			"PhysCrenata",
	// 			"HaiMast3r",
	// 			"Youkan5101",
	// 			"_greencat_",
	// 			"Cammo_353",
	// 			"CYR______",
	// 			"OkCya",
	// 			"ZennyTV",
	// 			"nequil",
	// 			"Hotdogchria"
	// 		]
	// 	},
	// 	"WC44": {
	// 		"firstSeen": 1713063327523,
	// 		"players": [
	// 			"Kayde_Official",
	// 			"Evemy",
	// 			"KZGtaye",
	// 			"UwUGamer007",
	// 			"DR_saltshaker",
	// 			"EKOHC",
	// 			"Stanley_Chen",
	// 			"ImEcho_",
	// 			"hahafunny37",
	// 			"Gavroxx",
	// 			"amun_rai",
	// 			"stogy115",
	// 			"potato_duck16",
	// 			"SuperbotOX",
	// 			"hakunagi314",
	// 			"striqz",
	// 			"GameKnightAndy",
	// 			1110110101,
	// 			"Icenka_Gamer",
	// 			"snakebr0",
	// 			"neversmoke",
	// 			"skyrimfan1",
	// 			"Ryo_tele2456",
	// 			"kei_kou_",
	// 			"_wuki_",
	// 			"Danh_005",
	// 			"junhang_lee1",
	// 			"Rusty_Bubble",
	// 			"Amitajun",
	// 			"Xyruh"
	// 		]
	// 	},
	// 	"WC26": {
	// 		"firstSeen": 1713043172968,
	// 		"players": [
	// 			"bendstandingman",
	// 			"tappy1045",
	// 			"Pocabu",
	// 			"ThomasTRO_",
	// 			"StePlays",
	// 			"elmost1",
	// 			"ile123ile",
	// 			"CodeJock42069",
	// 			"d4ark4angel",
	// 			"pentahedron",
	// 			"__Minor__",
	// 			"bobby686868",
	// 			"skrybs",
	// 			"Rowebbs",
	// 			"Fqpq",
	// 			"Az011",
	// 			"flyingducks777",
	// 			"Sea0tter_",
	// 			"FungeonKeeper",
	// 			"CoweCat",
	// 			"geenee10",
	// 			"LuxRow1",
	// 			"Cameron62",
	// 			"Luvln",
	// 			"feruram",
	// 			"Le_Boi123",
	// 			"leakytoe"
	// 		]
	// 	},
	// 	"WC32": {
	// 		"firstSeen": 1713060870865,
	// 		"players": [
	// 			"Sykrvll",
	// 			"Korinya",
	// 			"KoalaPro07",
	// 			"Sane_Tempest",
	// 			"Nimble_Deer",
	// 			"Zomadan",
	// 			"PicklePiePro",
	// 			"pengen1",
	// 			"RedstoneProGamer",
	// 			"MKnotJFK",
	// 			"Ceobe_yyds",
	// 			"Harmonance",
	// 			"VolumRPG",
	// 			"SnowTrunks",
	// 			"SecretionThief",
	// 			"Delicy18",
	// 			"boniebel",
	// 			"JellyByte",
	// 			"RobSmurdaa",
	// 			"Zeeye",
	// 			"Happy_Dayo",
	// 			"Kazemi_Ayaha",
	// 			"nekoron5041",
	// 			"CoopyTroopy21",
	// 			"Sorukekorashoman",
	// 			"Quiznq",
	// 			"_thedealer_",
	// 			"_f1Lthz4",
	// 			"Redzel",
	// 			"Frat_Boyz"
	// 		]
	// 	},
	// 	"WC5": {
	// 		"firstSeen": 1713044604600,
	// 		"players": [
	// 			"MrBozini",
	// 			"soler3",
	// 			"Pododeng",
	// 			"i_am_farrah",
	// 			"26mhu",
	// 			"Shararamoshik",
	// 			"U_matter",
	// 			"DEAD_SHOT2011",
	// 			"yot",
	// 			"Didder_",
	// 			"elighten",
	// 			"Tunium",
	// 			"Marius_Dao",
	// 			"nuser3",
	// 			"BongoBongoBongo",
	// 			"PencilThief",
	// 			"Lightning64",
	// 			"Splash_Gradation",
	// 			"Dy_",
	// 			"FinnFindlay",
	// 			"Linaxox",
	// 			"fennectech",
	// 			"Cqyle",
	// 			"Zexoria",
	// 			"brog_us",
	// 			"Samredstone",
	// 			"MinhtyTime",
	// 			"SpinaRosam",
	// 			"heodang12"
	// 		]
	// 	},
	// 	"WC19": {
	// 		"firstSeen": 1713060531138,
	// 		"players": [
	// 			"Nonchucks",
	// 			"ToastAnimate",
	// 			"DurJak",
	// 			"ka121",
	// 			"Astropeanutbuttr",
	// 			"orangutan_poop",
	// 			"Walkless",
	// 			"Dude__Guy",
	// 			"Diableg",
	// 			"Setoka7",
	// 			"AtlasOpus",
	// 			"IgnitusDragon442",
	// 			"Voramok573",
	// 			"Abo7md_xpro",
	// 			"JustTornado",
	// 			"PlayerSlayer1998",
	// 			"TimeValley",
	// 			"CrustyGoatCheese",
	// 			"AllGudNamesGone",
	// 			"timeforfrog",
	// 			"HakuKatla",
	// 			"derpytron5000",
	// 			"madzeN115",
	// 			"Kenai77",
	// 			"masaki0429",
	// 			"puppah",
	// 			"IncinerateMe",
	// 			"_cool_steve_",
	// 			"max267",
	// 			"Person8790",
	// 			"ImaJC",
	// 			"DandiestTrack66",
	// 			"cuteboy23456666",
	// 			"UchiHahahaha",
	// 			"kpolr",
	// 			"Theyyk"
	// 		]
	// 	},
	// 	"WC41": {
	// 		"firstSeen": 1713044231922,
	// 		"players": [
	// 			"notazu",
	// 			"Cledward",
	// 			"jonjon286",
	// 			"Rire3",
	// 			"Ayayka",
	// 			"49mg",
	// 			"Rockargen",
	// 			"cavera76",
	// 			"Prongl",
	// 			"ModeloDaLOreal",
	// 			"rockbusterbg",
	// 			"Salzmanderzz",
	// 			"Doubledash08",
	// 			"Luanex",
	// 			"Snownlite",
	// 			"HumanityOK",
	// 			"juria0",
	// 			"Gummybear1121",
	// 			"GomjelliMakeutu",
	// 			"RitualRaven",
	// 			"LovelyMoca",
	// 			"Turttlezs",
	// 			"maeu_",
	// 			"Umbraleviathan",
	// 			"Froppii_",
	// 			"Myunari",
	// 			"Pdak",
	// 			"_IlyCarrot",
	// 			"4Kyro",
	// 			"ToboCoolMan2000",
	// 			"LordMeGusta",
	// 			"Astere0n",
	// 			"Noxer69"
	// 		]
	// 	},
	// 	"WC24": {
	// 		"firstSeen": 1713063202432,
	// 		"players": [
	// 			"MICHAELXHCA",
	// 			"BitPlayer8147",
	// 			"LookAtMe_XD",
	// 			"TOOKEN_",
	// 			"wiitard",
	// 			"soileddirt",
	// 			"warzone741",
	// 			"qiushan1216",
	// 			"OPTanksteel",
	// 			"konhiro247",
	// 			"KillaLalas",
	// 			"Zaglington",
	// 			"ReallyUncool",
	// 			"DropIt",
	// 			"3Pie",
	// 			"_2u",
	// 			"SilverWarSi",
	// 			"cyberia99",
	// 			"Bnnui",
	// 			"Borzah",
	// 			"NSL_Wryyyyy",
	// 			"Deadpan43",
	// 			"LastIsAFK",
	// 			"Phinx",
	// 			"Acid_07",
	// 			"papurika1024",
	// 			"WHAFFLEZ_",
	// 			"Nyethal",
	// 			"tatty5678",
	// 			"LogicalHawk5"
	// 		]
	// 	},
	// 	"WC30": {
	// 		"firstSeen": 1713057076386,
	// 		"players": [
	// 			"BlackDarkness419",
	// 			"reeefleks",
	// 			"Arquerodark1",
	// 			"isaaciscrying",
	// 			"Glow_pup",
	// 			"RemiaHippo",
	// 			"orenge_",
	// 			"BigCatRescue",
	// 			"Albhis",
	// 			"hnnl",
	// 			"Pingu_7",
	// 			"Gee_55",
	// 			"k0_Fu",
	// 			"coffincrow",
	// 			"LionCrafter64",
	// 			"KennvRave",
	// 			"XXIcedxX",
	// 			"Rurinkitoz",
	// 			"01_",
	// 			"DogeLife367",
	// 			"convolvulus",
	// 			"GabrielEF",
	// 			"Bunnah",
	// 			"PainlessStorage1",
	// 			"MOMOneko7",
	// 			"Kraetys",
	// 			"OGC__",
	// 			"MadLad63"
	// 		]
	// 	},
	// 	"WC47": {
	// 		"firstSeen": 1713038201970,
	// 		"players": [
	// 			"DevilPlays10",
	// 			"DarkestKnight6",
	// 			"GoneClassy",
	// 			"Monkeykapaa",
	// 			"Burnt_Toast68",
	// 			"PastorRacoon",
	// 			"Vxxed888",
	// 			"Rapid22",
	// 			"BumptyDumpty",
	// 			"MomWood",
	// 			"Skyrkazm",
	// 			"earcra0106",
	// 			"FizzyPlayz28",
	// 			"Ca2lumG",
	// 			"SunbreakTitan07",
	// 			"Dragon4564",
	// 			"grey833",
	// 			"just_in_time87",
	// 			"soymilkluce",
	// 			"lilly_four",
	// 			"ZmanMythhead",
	// 			"yFelipeMC_",
	// 			"KobaHemm",
	// 			"maplu"
	// 		]
	// 	},
	// 	"WC16": {
	// 		"firstSeen": 1713042239314,
	// 		"players": [
	// 			"Lqna",
	// 			"Toi1et",
	// 			"Cylestialstar",
	// 			"TravelerMerchant",
	// 			"cjtrahan2005",
	// 			"Giluzarku37427",
	// 			"jiru6552",
	// 			"crounon",
	// 			"GrubbierAsp",
	// 			"Nooby13",
	// 			"Kirby219",
	// 			"Antonemy",
	// 			"Jbote87",
	// 			"RadiantZelda",
	// 			"m3atkn1ght",
	// 			"Rare_frog",
	// 			"jordanspiteri",
	// 			"MrBobQK",
	// 			"Tac0Tim3",
	// 			"AddictedGamer817",
	// 			"al10000",
	// 			"ButteryCream",
	// 			"kiryukazum",
	// 			"catsimpact08",
	// 			"attc",
	// 			"Meesz",
	// 			"File",
	// 			"Racejet",
	// 			"YayaJunOO",
	// 			"mqxxd",
	// 			"arranblue"
	// 		]
	// 	},
	// 	"WC31": {
	// 		"firstSeen": 1713043485829,
	// 		"players": [
	// 			"poopoolagoon",
	// 			"GottaGoFatteh",
	// 			"ChanceOfWin",
	// 			"crazydeadpool247",
	// 			"rrjol1209",
	// 			"Breezywilliams0",
	// 			"_Reimos",
	// 			"TheV3ntu5",
	// 			"TNTBumblebee",
	// 			"_Snowy_0y",
	// 			"Hitonano18",
	// 			"PinkShaze",
	// 			"98ml",
	// 			"TeTe8y",
	// 			"Trakoriis",
	// 			"LawnMower999",
	// 			"Aquatn",
	// 			"Rabbit_flower",
	// 			"NitrousSilver",
	// 			"iampro14",
	// 			"hahaTravel",
	// 			"buckasaurousrex",
	// 			"CuriousKaze",
	// 			"IQ5_No_Otoko",
	// 			"TheDogalaxy"
	// 		]
	// 	},
	// 	"WC2": {
	// 		"firstSeen": 1713040372211,
	// 		"players": [
	// 			"Wiscat17",
	// 			"iylx",
	// 			"AlphaT3ch",
	// 			"Soul_Retriever",
	// 			"TTYEET4912",
	// 			"SecretID_",
	// 			"skellington12",
	// 			"MiqoT",
	// 			"164ovo",
	// 			"eliix_x",
	// 			"FelineKarma85_jp",
	// 			"XylemPalce",
	// 			"CreatorGator",
	// 			"thecanfer",
	// 			"kkuuyyiinn",
	// 			"Shadow_Katt",
	// 			"Alpyg",
	// 			"J1_jp",
	// 			"nishaku200",
	// 			"SuperCheesyGamin",
	// 			"Suiseich",
	// 			"kuni_7",
	// 			"Orb1t18",
	// 			"VivioliRavioli"
	// 		]
	// 	},
	// 	"WC40": {
	// 		"firstSeen": 1713034967557,
	// 		"players": [
	// 			"Arch_N0ob_mAstr",
	// 			"hlickyalf",
	// 			"SkinnyAsianBoy",
	// 			"Obstacles_",
	// 			"Illumizeira",
	// 			"meowmeomeowmew",
	// 			"xruiva",
	// 			"Rustivard",
	// 			"Cymmerii",
	// 			"SovCunha",
	// 			"JvstMango",
	// 			"aeraLI",
	// 			"Konenala21",
	// 			"Knightslayer105",
	// 			"AzzyBee",
	// 			"Azift",
	// 			"Starkinho",
	// 			"errorpotato404",
	// 			"Xu_Feng_xdn",
	// 			"TheGoldenHusky",
	// 			"ozouni2485",
	// 			"Bagel360",
	// 			"aetriku",
	// 			"Pight_"
	// 		]
	// 	},
	// 	"WC7": {
	// 		"firstSeen": 1713036613910,
	// 		"players": [
	// 			"FnrEnder",
	// 			"CookiChan",
	// 			"MGamer404",
	// 			"MeoVT",
	// 			"KayKayST",
	// 			"Jrmble",
	// 			"trickyanthony",
	// 			"Al_Shehhi",
	// 			"ereMMVII",
	// 			"Vexorphius",
	// 			"Negitive_545",
	// 			"Keskaflow",
	// 			"rhinonick",
	// 			"ganadorph1",
	// 			"Budd3r4dawin",
	// 			"heyventix",
	// 			"WIZander",
	// 			"AngelFxre",
	// 			"biography",
	// 			"lucy8228",
	// 			"CrusadeSchools"
	// 		]
	// 	},
	// 	"WC23": {
	// 		"firstSeen": 1713037487033,
	// 		"players": [
	// 			"atawarudeath",
	// 			"ree8134515",
	// 			"TheGuardian693",
	// 			"Black_holy",
	// 			"Pokecrafter1204",
	// 			"minimaster419",
	// 			"WIllFandofer",
	// 			"7achyon",
	// 			"SweetCheeks_",
	// 			"yazeedissleepy",
	// 			"Dominox3",
	// 			"Shiny12",
	// 			"PomfPomfKimochi",
	// 			"keallor",
	// 			"ballchinianSc",
	// 			"MP3PLAY",
	// 			"masCreature",
	// 			"_Sault_",
	// 			"Plachez",
	// 			"BlueCorundum",
	// 			"immortalartisan",
	// 			"Dragostormer",
	// 			"TSBlader"
	// 		]
	// 	},
	// 	"WC6": {
	// 		"firstSeen": 1713040992999,
	// 		"players": [
	// 			"izzy4234",
	// 			"JMarsson28",
	// 			"linnyflower",
	// 			"dpsKokomi",
	// 			"YotamiDW",
	// 			"Kyian1225",
	// 			"Boltified",
	// 			"ppfart",
	// 			"Celesty0",
	// 			"Lallabella",
	// 			"Shireee",
	// 			"Anan5451",
	// 			"atchziens",
	// 			"Dannyxv8",
	// 			"bubblyAnime",
	// 			"FuhQx",
	// 			"Ekco",
	// 			"salyoutations",
	// 			"BlockBusss",
	// 			"Nynnf",
	// 			"Camden",
	// 			"Saphyris",
	// 			"iitzz_Dark",
	// 			"_Pain_Less_",
	// 			"AtomUnKnown",
	// 			"Felixstew",
	// 			"Pajama_Day",
	// 			"SilverSCore",
	// 			"Tom_Record",
	// 			"elroketson",
	// 			"TheRealTyco",
	// 			"EliteDuelist",
	// 			"1nfinity_",
	// 			"JKLDragon",
	// 			"BadNewsBears",
	// 			"Ayreseraph",
	// 			"YOUBETERUN",
	// 			"heart6008"
	// 		]
	// 	},
	// 	"WC29": {
	// 		"firstSeen": 1713060654853,
	// 		"players": [
	// 			"FireFly833",
	// 			"MissMeowMeowKat",
	// 			"IghorSantos",
	// 			"Pyrophany",
	// 			"Panadian",
	// 			"Jusslmao",
	// 			"EveofMadness",
	// 			"livlivlivia",
	// 			"LunarPixelOne",
	// 			"zhuzhuOwO",
	// 			"Crussant",
	// 			"Legomyeggominer",
	// 			"DankWetworkX",
	// 			"Joran_1337",
	// 			"ggonthemic",
	// 			"Wolfy5life",
	// 			"Emeraldsdsdsd",
	// 			"Jonathan45678",
	// 			"Kuro0929",
	// 			"Fatals_",
	// 			"WalnutChunk6181",
	// 			"meefy_",
	// 			"hackblackakm",
	// 			"CUjico",
	// 			"Zaynte",
	// 			"ArtistryMachine",
	// 			"buntails",
	// 			"rizi04b",
	// 			"thegekka",
	// 			"Arkarium",
	// 			"Mxxses",
	// 			"roKotine",
	// 			"ItsCatLmao",
	// 			"CorruptedLily"
	// 		]
	// 	},
	// 	"WC13": {
	// 		"firstSeen": 1713010628615,
	// 		"players": [
	// 			"KingLeonBrave",
	// 			"DinnerFast",
	// 			"ggsuru99",
	// 			"Inferiordude97",
	// 			"Lettereeno",
	// 			"CMPro",
	// 			"Trashed_Dumpster",
	// 			"Wystana",
	// 			"kirzem",
	// 			"MuchAwesomeboii",
	// 			"Hamster_God123",
	// 			"TheChancellor",
	// 			"Bubbalicious08",
	// 			"ReaperxArrow",
	// 			"vicodinL9",
	// 			"CyclopsMan0926",
	// 			"slashbin",
	// 			"planner1",
	// 			"jwtbh",
	// 			"Ipnotizzatore",
	// 			"BirchStarr",
	// 			"Magic_Avocado",
	// 			"Biam",
	// 			"Shear",
	// 			"Greundgul",
	// 			"LazyDergenBoi",
	// 			"Corbit",
	// 			"BirdyBlaze"
	// 		]
	// 	},
	// 	"WC39": {
	// 		"firstSeen": 1713031240687,
	// 		"players": [
	// 			"Reformed_Panda",
	// 			"Dominances",
	// 			"Ryzen239",
	// 			"Averted2",
	// 			"Cyro_gamez",
	// 			"Mrpicklesworth85",
	// 			"HeyGoat",
	// 			"xiaowu_666",
	// 			"LeafSaturation",
	// 			"LittleLapine",
	// 			"Hitmonlee",
	// 			"hcelestee",
	// 			"Camillerir",
	// 			"The_Toasticorn"
	// 		]
	// 	},
	// 	"WC8": {
	// 		"firstSeen": 1713041179752,
	// 		"players": [
	// 			"Kensu_Sama",
	// 			"ahrylai_03",
	// 			"Youngjuice2",
	// 			"dragonslash123",
	// 			"Draggon_Roll",
	// 			"Ragnarok11",
	// 			"Biblonko",
	// 			"6ec",
	// 			"AmazingMina",
	// 			"Boltoi",
	// 			"FinnckMalos",
	// 			"itizyou",
	// 			"_runaan",
	// 			"LososCroissant",
	// 			"EagleMNF",
	// 			"monkeybug34",
	// 			"danieltlq",
	// 			"cup1927",
	// 			"Artmis_Night",
	// 			"Macaroni2550",
	// 			"_XRN_",
	// 			"Hallucinations13",
	// 			"Ugastag",
	// 			"Vicano"
	// 		]
	// 	}
	// })
	// const [worlds, setWorlds] = useState({
	// 	"WC38": {
	// 		"firstSeen": 1713062705563,
	// 		"players": [
	// 			"Coolkid1206",
	// 			"RevolvingOcelot",
	// 			"Simpmulation",
	// 			"ZipperDeer",
	// 			"Vulpix1",
	// 			"ReisBlau",
	// 			"danot",
	// 			"KodaAndKeyno",
	// 			"hunter2776",
	// 			"Stunbud",
	// 			"InkedSk8ter",
	// 			"nChaine",
	// 			"MrQBurt",
	// 			"TFoxy13",
	// 			"TheLordXerxes",
	// 			"takayama_bros",
	// 			"FelixTape",
	// 			"yotaaaaa",
	// 			"Humongoustea178",
	// 			"Drawss",
	// 			"Bas_Tech",
	// 			"tararaco",
	// 			"FluffyPixel9",
	// 			"Fanxiang",
	// 			"JustJeffery",
	// 			"Ed3l",
	// 			"swimwater",
	// 			"LionKing421",
	// 			"Lemonsan666",
	// 			"0MNlV0RE",
	// 			"Syfilen"
	// 		]
	// 	},
	// 	"WC43": {
	// 		"firstSeen": 1713061711279,
	// 		"players": [
	// 			"Gamerboy1322020",
	// 			"DuskyDusky",
	// 			"KMsan",
	// 			"Crimsondevilsin",
	// 			"catg1rl",
	// 			"Luna__Prism",
	// 			"Henry_814",
	// 			"ThatFortniteGuy",
	// 			"Oldfox39",
	// 			"PKfreeze123",
	// 			"readly44",
	// 			"SaffronCSF",
	// 			"N0tChris",
	// 			"dizaster6th",
	// 			"Its_Meh",
	// 			"Chambers02",
	// 			"diamond_slayer5",
	// 			"Prowombat3",
	// 			"TheBryard",
	// 			"brqndonn",
	// 			"punscake",
	// 			"Frozzx3102",
	// 			"NokaHoa",
	// 			"StayALIV3",
	// 			"hoMiroNg",
	// 			"Woealer",
	// 			"Cruuk",
	// 			"cluster_amarylli",
	// 			"CrescentedFish",
	// 			"IcarusDies",
	// 			"Lucid_Hope",
	// 			"muzf"
	// 		]
	// 	},
	// 	"WC42": {
	// 		"firstSeen": 1713063076995,
	// 		"players": [
	// 			"cerealki11ing",
	// 			"koiifish_",
	// 			"sharpieaddictt",
	// 			"goombas_killer",
	// 			"Le_Patito",
	// 			"lopro2010",
	// 			"XXMVNM123",
	// 			"Meniscussssss",
	// 			"Griimmmm",
	// 			"ScytheOfLife",
	// 			"Artificed",
	// 			"_Commander_Ike_",
	// 			"theSparkalina",
	// 			"pugman421",
	// 			"BoyofLength",
	// 			"cam06060",
	// 			"Debauche",
	// 			"brilliantknight",
	// 			"Princ3Victor",
	// 			"Solublee",
	// 			"yoshro27",
	// 			"gobert_rl",
	// 			"FireBlux3",
	// 			"azhuuk",
	// 			"TastyJason",
	// 			"Taiwan_is_first",
	// 			"monkeysorcerer2",
	// 			"yayo2016",
	// 			"FluffyCape87348",
	// 			"13Amicus",
	// 			"Lrum"
	// 		]
	// 	},
	// 	"WC10": {
	// 		"firstSeen": 1713046407836,
	// 		"players": [
	// 			"migu31",
	// 			"Rd_Ctrlr",
	// 			"ZaiSama_",
	// 			"JimbiFist",
	// 			"isakax",
	// 			"_sni7ch",
	// 			"MaxTm8",
	// 			"ThDestr",
	// 			"Peytondude8",
	// 			"Doge4517",
	// 			"zMars",
	// 			"ningbun",
	// 			"mosquitokill",
	// 			"Aggusteen",
	// 			"RipleyTheAxolotl",
	// 			"nerdynerdz",
	// 			"Lastly",
	// 			"Cajahope",
	// 			"MasterKaboom",
	// 			"UnluckyPill",
	// 			"Necryo_",
	// 			"dollbite",
	// 			"UnVanilla",
	// 			"aqua0763",
	// 			"EchoingGryffin",
	// 			"xTheRedx",
	// 			"jorge_ivan123",
	// 			"vasectomylover2",
	// 			"BakaUnicorn14",
	// 			"IsseiHDxD",
	// 			"Thira8",
	// 			"_Toos_",
	// 			"oseyuki",
	// 			"Orphion_"
	// 		]
	// 	},
	// 	"WC1": {
	// 		"firstSeen": 1713041989209,
	// 		"players": [
	// 			"kitsunyaaaa",
	// 			"igambleinchat",
	// 			"Pokiie",
	// 			"PIXEL_POSTER",
	// 			"MrJulianB0T",
	// 			"oKlaws_",
	// 			"Aovhii",
	// 			"ablockofdort",
	// 			"Owieczka15",
	// 			"OppositeMirror",
	// 			"Error_402",
	// 			"Aureuix",
	// 			"5ura",
	// 			"PlasmaWarrior",
	// 			"PaisleyBiscuit",
	// 			"TrNyxo",
	// 			"BatClub",
	// 			"leonatcam",
	// 			"MCPro_Gamer",
	// 			"Irredescent",
	// 			"Forever_Night1",
	// 			"IFionnaI_",
	// 			"beurfus",
	// 			"Manoogi",
	// 			"2000IQ",
	// 			"NeverForgetten",
	// 			"Fishbasket74",
	// 			"JldwL",
	// 			"wilsan3",
	// 			"jacobwfvp1",
	// 			"G0ldenR0uoxls"
	// 		]
	// 	},
	// 	"WC17": {
	// 		"firstSeen": 1713048430984,
	// 		"players": [
	// 			11721172,
	// 			"LordGonner",
	// 			"Dorian_Marwood",
	// 			"_B3N450_",
	// 			"OmegaInbound",
	// 			"nickbraves1",
	// 			"twining_t86",
	// 			"WoodHolland",
	// 			"NasaNerd314",
	// 			"AkuroR7",
	// 			"DT_TKmVN",
	// 			"DT_Gura",
	// 			"Keqqu",
	// 			"WoodKast",
	// 			"DestroyManIV",
	// 			"vrodih",
	// 			"WoodVA",
	// 			"ThaWood",
	// 			"Incarceon_",
	// 			"WoodLost",
	// 			"Gombreng",
	// 			"WoodCreature",
	// 			"Jopher11733",
	// 			"SrReikuz",
	// 			"OmTaoEinsofManus",
	// 			"LaDvdCorzo",
	// 			"DT_Jack",
	// 			"WoodXP",
	// 			"PingouinDLS",
	// 			"SentryPickle",
	// 			"Voidarcher72",
	// 			"Cucho2910"
	// 		]
	// 	},
	// 	"WC27": {
	// 		"firstSeen": 1713059876644,
	// 		"players": [
	// 			"DanOldMan",
	// 			"Nomadixc",
	// 			"succbucket",
	// 			"meltingiam",
	// 			"ReeceReineke",
	// 			"Rade_emear",
	// 			"VetroFPS",
	// 			"FlowerPrincess",
	// 			"GerberaSymphony",
	// 			"Patro633",
	// 			"ScalesInSweaters",
	// 			"KN1GHTFALL",
	// 			"white_boy",
	// 			"CosmobbleSys",
	// 			"RAYAXY",
	// 			"oHate",
	// 			"VolkyPolky",
	// 			"BlakeDwarf",
	// 			"Nnama",
	// 			"IsaacDelta",
	// 			"FoxShr00m",
	// 			"feiPC123",
	// 			"Drbiznes",
	// 			"Baj_Baj",
	// 			"HiSlIgHt_",
	// 			"kristyboo",
	// 			"meemmeem1",
	// 			"oGeoff",
	// 			"icehawk54",
	// 			"Montews"
	// 		]
	// 	},
	// 	"WC36": {
	// 		"firstSeen": 1713030334852,
	// 		"players": [
	// 			"Yoonami",
	// 			"FireRex206966",
	// 			"Bosukude4649",
	// 			"Xzazel",
	// 			"Ewen_Le_Nain",
	// 			"egg4059",
	// 			"Nines_Own_Goal",
	// 			"WhiteNoise0113",
	// 			"EririLovegold",
	// 			"H4iKiri",
	// 			"HaNdY__",
	// 			"YufanC",
	// 			"itsdannyright"
	// 		]
	// 	},
	// 	"WC21": {
	// 		"firstSeen": 1713050547196,
	// 		"players": [
	// 			"LeLazi",
	// 			"Masojia_jp",
	// 			"Mihaukse",
	// 			"facelessgoat11",
	// 			"Dwaam",
	// 			"heiru6199",
	// 			"FluffySeal2988",
	// 			"PengosPongos",
	// 			"Univerouse",
	// 			"ihyukai",
	// 			"UhSnap",
	// 			"lil_headass",
	// 			"C4MERONXOX",
	// 			"_topaz",
	// 			"Spenchilada",
	// 			"Enick",
	// 			"DanOninho_",
	// 			"PerUnknown",
	// 			"Calluum",
	// 			"aDri9101",
	// 			"NKiritoN",
	// 			"King__Bob",
	// 			"IEA1000",
	// 			"Ethos999",
	// 			"adri88g",
	// 			"CatPlayingGames",
	// 			"BluBlueJay"
	// 		]
	// 	},
	// 	"WC28": {
	// 		"firstSeen": 1713037547549,
	// 		"players": [
	// 			"ObxM",
	// 			"Temtem_TS",
	// 			"Sumaho1008",
	// 			"DragxD",
	// 			"BuffJadeMining",
	// 			"Toasty_boi",
	// 			"Eshreal",
	// 			"Stil_",
	// 			"pugacy",
	// 			"Ruekimou",
	// 			"NotsoDumb",
	// 			"SP1_Dragon",
	// 			"Whath",
	// 			"Doggc",
	// 			"Cal_and_Ben",
	// 			"GooseCore",
	// 			"Sand_V3",
	// 			"TKW256",
	// 			"xSuzu",
	// 			"SilverlyNight",
	// 			"_Thinking_Face_",
	// 			"Blademaster0",
	// 			"Jasonplayzz",
	// 			"TheNelston",
	// 			"kubawu_",
	// 			"Oblong_Sushi",
	// 			"allizhi"
	// 		]
	// 	},
	// 	"WC18": {
	// 		"firstSeen": 1713052317725,
	// 		"players": [
	// 			"IDontLikeToDie",
	// 			"Shebn",
	// 			"VaadVaati",
	// 			"CitraSama",
	// 			"Scarlet_to_dream",
	// 			"YouAreRexist",
	// 			"badsoup",
	// 			"jaxonishere",
	// 			"Son_Of_Walter",
	// 			"minebrine10",
	// 			"GudSpeling",
	// 			"Black_Scorpion_",
	// 			"Colinix",
	// 			"Conan0LM",
	// 			"angycathy",
	// 			"yhtacygna",
	// 			"crafttatsuya",
	// 			"RanaKikker",
	// 			"xyrily",
	// 			"SleepyMistix",
	// 			"fangtianxing",
	// 			"Wynderia",
	// 			"Zatch",
	// 			"HRJDragon",
	// 			"Felirya"
	// 		]
	// 	},
	// 	"WC20": {
	// 		"firstSeen": 1713045226538,
	// 		"players": [
	// 			"Super_Sharkie",
	// 			"Mxxrm",
	// 			"maikeru34",
	// 			"lecie4",
	// 			"KeyWe_87_island",
	// 			"svinerus",
	// 			"GaboMcGamer",
	// 			"noateto1",
	// 			"Jenica",
	// 			"JessicaPink703",
	// 			"AdmiralDaizin",
	// 			"HimesakaLuna",
	// 			"XeiroFlora",
	// 			"Vzax",
	// 			"jaygoddd",
	// 			"Act1vateWindows",
	// 			"takasin1",
	// 			"NinjaChicken95",
	// 			"FancyKiwi",
	// 			"PartlySunny",
	// 			"Gensubaru",
	// 			"boyfrom",
	// 			"mikeworld3",
	// 			"R_Ruffles",
	// 			"TinyRedRaceCar",
	// 			"Oyasai_JE9100"
	// 		]
	// 	},
	// 	"WC9": {
	// 		"firstSeen": 1713037080442,
	// 		"players": [
	// 			"OrphanedChild",
	// 			"PimpleDimps",
	// 			"RTrinh563",
	// 			"Ahuizotll",
	// 			"RikuMochi",
	// 			"Qu3st1on",
	// 			"Ossydeussy",
	// 			"t4be",
	// 			"xXZaBriNgAXx",
	// 			"zJury",
	// 			"Cursed2w1",
	// 			"Paradision",
	// 			"sc2sr",
	// 			"Housery",
	// 			"RubMyMineshaft",
	// 			"p_b_d_matcha8931",
	// 			"DarkFeather556",
	// 			"xAkumi",
	// 			"SillyScrew",
	// 			"Azomth",
	// 			"yap_per",
	// 			"jia_qin",
	// 			"dog_eggs",
	// 			"Lemon_Pan",
	// 			"Mail_Watdaimod",
	// 			"FabDoesStuff",
	// 			"Nightslasher38",
	// 			"kyeun",
	// 			"AXYEHHOKPYTO",
	// 			"whiteguy48"
	// 		]
	// 	},
	// 	"WC37": {
	// 		"firstSeen": 1713050861666,
	// 		"players": [
	// 			"tummblez99",
	// 			"smaching",
	// 			"Frogstand",
	// 			"Techno_Guy_KWP",
	// 			"Ruinc",
	// 			"OverlordAlastor",
	// 			"SkimBeebs",
	// 			"WhiteFang__",
	// 			"YOKOKUMA",
	// 			"HeavyMetalHaven",
	// 			"TacoCat7653",
	// 			"ohitslemon",
	// 			"TakiCesar",
	// 			"BaggierTree3320",
	// 			"WestCandle_JP",
	// 			"wrubiix",
	// 			"Johnadam211212",
	// 			"Sub__Par",
	// 			"kai_chen0602",
	// 			"Zaidob",
	// 			"UnusualHeron",
	// 			"Fan2mario64",
	// 			"BarGam1",
	// 			"ryktcompassrose",
	// 			"MaybeLatah",
	// 			"TuLouis",
	// 			"Puurpleman",
	// 			"ElohmroW",
	// 			"Cataath"
	// 		]
	// 	},
	// 	"WC33": {
	// 		"firstSeen": 1713036613770,
	// 		"players": [
	// 			"TheZe_",
	// 			"IMagister",
	// 			"The_Big_Bunga",
	// 			"Mouseydavid10",
	// 			"Tqkened",
	// 			"LT_Universe",
	// 			"thatFishStick",
	// 			"ESTTGD",
	// 			"TheCloakMan",
	// 			"xx_bacon_man_xx",
	// 			"Rojeel",
	// 			"Iware_Pond",
	// 			"POPOPIYA",
	// 			"Mo1G4mez",
	// 			"Overvolt1000",
	// 			"SorrowfulLady",
	// 			"Skorm_Axebreaker",
	// 			"AWildHoshiyomi",
	// 			"mahiro1219",
	// 			"ProjectForceV2",
	// 			"rynf",
	// 			"ManMysterious",
	// 			"Brutakah",
	// 			"Red_Fox_Rogue",
	// 			"Crescentmoon621",
	// 			"falconthunder"
	// 		]
	// 	},
	// 	"WC14": {
	// 		"firstSeen": 1713059380165,
	// 		"players": [
	// 			"zeky",
	// 			"NOOBYPANDA_",
	// 			"Rahvin2007",
	// 			"Acorn11",
	// 			"Seraphim_Rayn",
	// 			"EpicWynn",
	// 			"Scarface_Connor",
	// 			"Ehsbii",
	// 			"Ulitiminer4172",
	// 			"xRisePunch",
	// 			"ekozi",
	// 			"MidNightMisT880",
	// 			"Nitroxlz",
	// 			"Ratalistic",
	// 			"Player6650",
	// 			"SnowFox166",
	// 			"EXARTIUS",
	// 			"aronkodol",
	// 			"Harm7",
	// 			"FraekInMuscle",
	// 			"Opmusic",
	// 			"thefugitiveminer",
	// 			"skyblueswordsman",
	// 			"TaKarir",
	// 			"nctrequiem",
	// 			"__Tempestissimo",
	// 			"RolleBolle55",
	// 			"ParasiticHelmint",
	// 			"Ventari_Wylde",
	// 			"pockt"
	// 		]
	// 	},
	// 	"WC35": {
	// 		"firstSeen": 1713050607784,
	// 		"players": [
	// 			"FaintCalf59547",
	// 			"DannyDanBoy",
	// 			"MERO_02",
	// 			"Blazedancer",
	// 			"illuminus_metam",
	// 			"sol798",
	// 			"Awkweat",
	// 			"SimplySlim3",
	// 			"Doctor_Whooves42",
	// 			"Jagaro",
	// 			"Gravetide",
	// 			"AnAceSpade",
	// 			"KREJ10",
	// 			"__bone__",
	// 			"cobalt771",
	// 			"jade_rabbit1124",
	// 			"Re0_Rem",
	// 			"ItsLionknight",
	// 			"0O0X0O0",
	// 			"McHimbo",
	// 			"PK2006",
	// 			"SassyGay",
	// 			"SueDillon",
	// 			"Chanwhun",
	// 			"KaoDremora",
	// 			"Smellbo_",
	// 			"Nightfury13",
	// 			"Jacobi102030",
	// 			"Greenbracelet",
	// 			"Volcanic_Gamer",
	// 			"Domisboss2014"
	// 		]
	// 	},
	// 	"WC15": {
	// 		"firstSeen": 1713041863547,
	// 		"players": [
	// 			"CaptainG2280",
	// 			"InozaAki_",
	// 			"Axyrius",
	// 			"Rita_87_island",
	// 			"SuperSein",
	// 			"Kneem",
	// 			"bluemidsdog",
	// 			"ABlack4",
	// 			"AtrejuPlays",
	// 			"driacore",
	// 			"dDANTE_S",
	// 			"Fleega",
	// 			"AreFeetShoes",
	// 			"TrissyTiger",
	// 			"Ataraxyia",
	// 			"KutekutoBonsai",
	// 			"LilacMasquerade",
	// 			"Arcellis",
	// 			"Marstrosity",
	// 			"TheMelonDragon",
	// 			"ILikeU",
	// 			"Murdery",
	// 			"PhyzzyBop",
	// 			"CrazyTiger12908",
	// 			"sbellebound",
	// 			"Mrblaze1301",
	// 			"uruy"
	// 		]
	// 	},
	// 	"WC12": {
	// 		"firstSeen": 1713057949533,
	// 		"players": [
	// 			"Fanta_lemonPie",
	// 			"Lord_Qwerty_Pyro",
	// 			"AlistorTheWolf",
	// 			"SpaceHusky17",
	// 			"Dragon_slayer820",
	// 			"sadgeleaf1",
	// 			"Starsxul",
	// 			"freeMCsmoke",
	// 			"zman1der",
	// 			"Chaioth_haQadesh",
	// 			"killaang",
	// 			"Vakama",
	// 			"danscorruption",
	// 			"x3n1",
	// 			"juli793",
	// 			"Jamal_meow",
	// 			"SPAC3M0NK3Y",
	// 			"Nekk0mancer",
	// 			"2Hero",
	// 			"wabey",
	// 			"chickrame",
	// 			"Drobicus",
	// 			"MortalMaximus",
	// 			"egyog",
	// 			"tsumikijenga_234",
	// 			"ChampionFighter",
	// 			"Clezynemy123",
	// 			"Dinhsiudeptrai",
	// 			"Tacosoftware9000",
	// 			"SinanBruh",
	// 			"Drawwy"
	// 		]
	// 	},
	// 	"WC22": {
	// 		"firstSeen": 1713037953076,
	// 		"players": [
	// 			"Blankown",
	// 			"vrdr",
	// 			"Legolucas1472",
	// 			"Fern_Ottors",
	// 			"Testo_",
	// 			"orangetofu",
	// 			"Stavrozius7",
	// 			"Lituk",
	// 			"TheAnonymousRain",
	// 			"daiebi14",
	// 			"defnotlexi",
	// 			"RazzorHDD",
	// 			"origamiking152",
	// 			"Jaggster",
	// 			"Weedow_",
	// 			"AutisticCrumbs",
	// 			"Rye21",
	// 			"sumituba4328",
	// 			"JammiestDodger",
	// 			"HX7D",
	// 			"Docokarra",
	// 			"oiSnow",
	// 			"FuturePlantsTM",
	// 			"Styx_He1ix",
	// 			"IgnisDragon",
	// 			"star473",
	// 			"ToucanTimm",
	// 			"omamesinzu",
	// 			"IIlShadowII",
	// 			"ItsJustKnoxx",
	// 			"Charlieoffps",
	// 			"catgirlviona",
	// 			"Dorothy62",
	// 			"Zerindal"
	// 		]
	// 	},
	// 	"WC34": {
	// 		"firstSeen": 1713042176818,
	// 		"players": [
	// 			"AndDrew_",
	// 			"latryxx",
	// 			"Duks",
	// 			"Trodeno",
	// 			"StealyOats",
	// 			"GooseTen",
	// 			"Capt_Fox241",
	// 			"VoraOfficial",
	// 			"Auri_El",
	// 			"Hyacinth_Oppop",
	// 			"GameHappy",
	// 			"IDoBeSimpingTho",
	// 			"odeska",
	// 			"Reser2207",
	// 			"bare__",
	// 			"TheEaf",
	// 			"FrostOffSum",
	// 			"GluePowa",
	// 			"Secret_FruityCat",
	// 			"BreadBurglar",
	// 			"inari080",
	// 			"kn8900",
	// 			"Poo_najak",
	// 			"PaLiNoxSR",
	// 			"CebuPacific",
	// 			"RaccoonLover9000",
	// 			"Monamiii",
	// 			"Run_O101",
	// 			"redpanda508"
	// 		]
	// 	},
	// 	"WC3": {
	// 		"firstSeen": 1713034563344,
	// 		"players": [
	// 			"Katalyst_x",
	// 			"Mirvam",
	// 			"Uoog",
	// 			"YerMumsDad",
	// 			"CrystalFlux",
	// 			"funkylezzo",
	// 			"SaibaKurokawa",
	// 			"AsianCat",
	// 			"gig4c4zo",
	// 			"Strife_Cloud",
	// 			"Forgetfulpass",
	// 			"Creampuffboy",
	// 			"MrGalacto",
	// 			"Daimax_19",
	// 			"Nooten_56",
	// 			"Mickaelhz",
	// 			"MoonAvem",
	// 			"thenumberonedud",
	// 			"Demonwes123",
	// 			"bobarken",
	// 			"Odogo",
	// 			"Wasasi",
	// 			"ixiclestinger22",
	// 			"MicrosRevenge",
	// 			"Hexodus",
	// 			"Damakos3"
	// 		]
	// 	},
	// 	"WC4": {
	// 		"firstSeen": 1713055616365,
	// 		"players": [
	// 			"ukcat68",
	// 			"MetalBox47",
	// 			"Flydane",
	// 			"morest",
	// 			"tonyloco13",
	// 			"JVRQ",
	// 			"rinobo1122",
	// 			"Super02starL",
	// 			"atomilogical",
	// 			"pnoot",
	// 			"Heidychyyy",
	// 			"MysticDireWolves",
	// 			"ItsLeafeon55",
	// 			"TheLukinator2022",
	// 			"KatskaBee",
	// 			"SarahLeSimp",
	// 			"FrootyToots",
	// 			"Xiissue",
	// 			"Gurdus",
	// 			"Doubletime_T",
	// 			"BliTZed_PaNdA",
	// 			"Mr_poopybutthole",
	// 			"Sir_Aaronymus",
	// 			"4nei",
	// 			"SleepyT2883",
	// 			"eatwithspork",
	// 			"MR_catalot",
	// 			"ImagineKami",
	// 			"helow127",
	// 			"Insighted",
	// 			"Sosit4",
	// 			"NinjaWasser",
	// 			"IamTheDuke"
	// 		]
	// 	},
	// 	"WC11": {
	// 		"firstSeen": 1713043607682,
	// 		"players": [
	// 			"Bennykelli1",
	// 			"Tis_awesomeness",
	// 			"SnUg3d",
	// 			"Wemydastore",
	// 			"GoodmanPasta",
	// 			"Whom_Asked",
	// 			"InfernalIE",
	// 			"derpsir",
	// 			"StreekSeyt",
	// 			"fj70",
	// 			"RamSimp",
	// 			"KSR2020",
	// 			"xXPoppa_WoodyXx",
	// 			"Dat808Taco",
	// 			"_Karsalesman_",
	// 			"Keldorn",
	// 			"bapafish",
	// 			"Tavahn",
	// 			"Pokeguy946",
	// 			"Beetown",
	// 			"PhysCrenata",
	// 			"HaiMast3r",
	// 			"Youkan5101",
	// 			"_greencat_",
	// 			"Cammo_353",
	// 			"CYR______",
	// 			"OkCya",
	// 			"ZennyTV",
	// 			"nequil",
	// 			"Hotdogchria"
	// 		]
	// 	},
	// 	"WC44": {
	// 		"firstSeen": 1713063327523,
	// 		"players": [
	// 			"Kayde_Official",
	// 			"Evemy",
	// 			"KZGtaye",
	// 			"UwUGamer007",
	// 			"DR_saltshaker",
	// 			"EKOHC",
	// 			"Stanley_Chen",
	// 			"ImEcho_",
	// 			"hahafunny37",
	// 			"Gavroxx",
	// 			"amun_rai",
	// 			"stogy115",
	// 			"potato_duck16",
	// 			"SuperbotOX",
	// 			"hakunagi314",
	// 			"striqz",
	// 			"GameKnightAndy",
	// 			1110110101,
	// 			"Icenka_Gamer",
	// 			"snakebr0",
	// 			"neversmoke",
	// 			"skyrimfan1",
	// 			"Ryo_tele2456",
	// 			"kei_kou_",
	// 			"_wuki_",
	// 			"Danh_005",
	// 			"junhang_lee1",
	// 			"Rusty_Bubble",
	// 			"Amitajun",
	// 			"Xyruh"
	// 		]
	// 	},
	// 	"WC26": {
	// 		"firstSeen": 1713043172968,
	// 		"players": [
	// 			"bendstandingman",
	// 			"tappy1045",
	// 			"Pocabu",
	// 			"ThomasTRO_",
	// 			"StePlays",
	// 			"elmost1",
	// 			"ile123ile",
	// 			"CodeJock42069",
	// 			"d4ark4angel",
	// 			"pentahedron",
	// 			"__Minor__",
	// 			"bobby686868",
	// 			"skrybs",
	// 			"Rowebbs",
	// 			"Fqpq",
	// 			"Az011",
	// 			"flyingducks777",
	// 			"Sea0tter_",
	// 			"FungeonKeeper",
	// 			"CoweCat",
	// 			"geenee10",
	// 			"LuxRow1",
	// 			"Cameron62",
	// 			"Luvln",
	// 			"feruram",
	// 			"Le_Boi123",
	// 			"leakytoe"
	// 		]
	// 	},
	// 	"WC32": {
	// 		"firstSeen": 1713060870865,
	// 		"players": [
	// 			"Sykrvll",
	// 			"Korinya",
	// 			"KoalaPro07",
	// 			"Sane_Tempest",
	// 			"Nimble_Deer",
	// 			"Zomadan",
	// 			"PicklePiePro",
	// 			"pengen1",
	// 			"RedstoneProGamer",
	// 			"MKnotJFK",
	// 			"Ceobe_yyds",
	// 			"Harmonance",
	// 			"VolumRPG",
	// 			"SnowTrunks",
	// 			"SecretionThief",
	// 			"Delicy18",
	// 			"boniebel",
	// 			"JellyByte",
	// 			"RobSmurdaa",
	// 			"Zeeye",
	// 			"Happy_Dayo",
	// 			"Kazemi_Ayaha",
	// 			"nekoron5041",
	// 			"CoopyTroopy21",
	// 			"Sorukekorashoman",
	// 			"Quiznq",
	// 			"_thedealer_",
	// 			"_f1Lthz4",
	// 			"Redzel",
	// 			"Frat_Boyz"
	// 		]
	// 	},
	// 	"WC5": {
	// 		"firstSeen": 1713044604600,
	// 		"players": [
	// 			"MrBozini",
	// 			"soler3",
	// 			"Pododeng",
	// 			"i_am_farrah",
	// 			"26mhu",
	// 			"Shararamoshik",
	// 			"U_matter",
	// 			"DEAD_SHOT2011",
	// 			"yot",
	// 			"Didder_",
	// 			"elighten",
	// 			"Tunium",
	// 			"Marius_Dao",
	// 			"nuser3",
	// 			"BongoBongoBongo",
	// 			"PencilThief",
	// 			"Lightning64",
	// 			"Splash_Gradation",
	// 			"Dy_",
	// 			"FinnFindlay",
	// 			"Linaxox",
	// 			"fennectech",
	// 			"Cqyle",
	// 			"Zexoria",
	// 			"brog_us",
	// 			"Samredstone",
	// 			"MinhtyTime",
	// 			"SpinaRosam",
	// 			"heodang12"
	// 		]
	// 	},
	// 	"WC19": {
	// 		"firstSeen": 1713060531138,
	// 		"players": [
	// 			"Nonchucks",
	// 			"ToastAnimate",
	// 			"DurJak",
	// 			"ka121",
	// 			"Astropeanutbuttr",
	// 			"orangutan_poop",
	// 			"Walkless",
	// 			"Dude__Guy",
	// 			"Diableg",
	// 			"Setoka7",
	// 			"AtlasOpus",
	// 			"IgnitusDragon442",
	// 			"Voramok573",
	// 			"Abo7md_xpro",
	// 			"JustTornado",
	// 			"PlayerSlayer1998",
	// 			"TimeValley",
	// 			"CrustyGoatCheese",
	// 			"AllGudNamesGone",
	// 			"timeforfrog",
	// 			"HakuKatla",
	// 			"derpytron5000",
	// 			"madzeN115",
	// 			"Kenai77",
	// 			"masaki0429",
	// 			"puppah",
	// 			"IncinerateMe",
	// 			"_cool_steve_",
	// 			"max267",
	// 			"Person8790",
	// 			"ImaJC",
	// 			"DandiestTrack66",
	// 			"cuteboy23456666",
	// 			"UchiHahahaha",
	// 			"kpolr",
	// 			"Theyyk"
	// 		]
	// 	},
	// 	"WC41": {
	// 		"firstSeen": 1713044231922,
	// 		"players": [
	// 			"notazu",
	// 			"Cledward",
	// 			"jonjon286",
	// 			"Rire3",
	// 			"Ayayka",
	// 			"49mg",
	// 			"Rockargen",
	// 			"cavera76",
	// 			"Prongl",
	// 			"ModeloDaLOreal",
	// 			"rockbusterbg",
	// 			"Salzmanderzz",
	// 			"Doubledash08",
	// 			"Luanex",
	// 			"Snownlite",
	// 			"HumanityOK",
	// 			"juria0",
	// 			"Gummybear1121",
	// 			"GomjelliMakeutu",
	// 			"RitualRaven",
	// 			"LovelyMoca",
	// 			"Turttlezs",
	// 			"maeu_",
	// 			"Umbraleviathan",
	// 			"Froppii_",
	// 			"Myunari",
	// 			"Pdak",
	// 			"_IlyCarrot",
	// 			"4Kyro",
	// 			"ToboCoolMan2000",
	// 			"LordMeGusta",
	// 			"Astere0n",
	// 			"Noxer69"
	// 		]
	// 	},
	// 	"WC24": {
	// 		"firstSeen": 1713063202432,
	// 		"players": [
	// 			"MICHAELXHCA",
	// 			"BitPlayer8147",
	// 			"LookAtMe_XD",
	// 			"TOOKEN_",
	// 			"wiitard",
	// 			"soileddirt",
	// 			"warzone741",
	// 			"qiushan1216",
	// 			"OPTanksteel",
	// 			"konhiro247",
	// 			"KillaLalas",
	// 			"Zaglington",
	// 			"ReallyUncool",
	// 			"DropIt",
	// 			"3Pie",
	// 			"_2u",
	// 			"SilverWarSi",
	// 			"cyberia99",
	// 			"Bnnui",
	// 			"Borzah",
	// 			"NSL_Wryyyyy",
	// 			"Deadpan43",
	// 			"LastIsAFK",
	// 			"Phinx",
	// 			"Acid_07",
	// 			"papurika1024",
	// 			"WHAFFLEZ_",
	// 			"Nyethal",
	// 			"tatty5678",
	// 			"LogicalHawk5"
	// 		]
	// 	},
	// 	"WC30": {
	// 		"firstSeen": 1713057076386,
	// 		"players": [
	// 			"BlackDarkness419",
	// 			"reeefleks",
	// 			"Arquerodark1",
	// 			"isaaciscrying",
	// 			"Glow_pup",
	// 			"RemiaHippo",
	// 			"orenge_",
	// 			"BigCatRescue",
	// 			"Albhis",
	// 			"hnnl",
	// 			"Pingu_7",
	// 			"Gee_55",
	// 			"k0_Fu",
	// 			"coffincrow",
	// 			"LionCrafter64",
	// 			"KennvRave",
	// 			"XXIcedxX",
	// 			"Rurinkitoz",
	// 			"01_",
	// 			"DogeLife367",
	// 			"convolvulus",
	// 			"GabrielEF",
	// 			"Bunnah",
	// 			"PainlessStorage1",
	// 			"MOMOneko7",
	// 			"Kraetys",
	// 			"OGC__",
	// 			"MadLad63"
	// 		]
	// 	},
	// 	"WC47": {
	// 		"firstSeen": 1713038201970,
	// 		"players": [
	// 			"DevilPlays10",
	// 			"DarkestKnight6",
	// 			"GoneClassy",
	// 			"Monkeykapaa",
	// 			"Burnt_Toast68",
	// 			"PastorRacoon",
	// 			"Vxxed888",
	// 			"Rapid22",
	// 			"BumptyDumpty",
	// 			"MomWood",
	// 			"Skyrkazm",
	// 			"earcra0106",
	// 			"FizzyPlayz28",
	// 			"Ca2lumG",
	// 			"SunbreakTitan07",
	// 			"Dragon4564",
	// 			"grey833",
	// 			"just_in_time87",
	// 			"soymilkluce",
	// 			"lilly_four",
	// 			"ZmanMythhead",
	// 			"yFelipeMC_",
	// 			"KobaHemm",
	// 			"maplu"
	// 		]
	// 	},
	// 	"WC16": {
	// 		"firstSeen": 1713042239314,
	// 		"players": [
	// 			"Lqna",
	// 			"Toi1et",
	// 			"Cylestialstar",
	// 			"TravelerMerchant",
	// 			"cjtrahan2005",
	// 			"Giluzarku37427",
	// 			"jiru6552",
	// 			"crounon",
	// 			"GrubbierAsp",
	// 			"Nooby13",
	// 			"Kirby219",
	// 			"Antonemy",
	// 			"Jbote87",
	// 			"RadiantZelda",
	// 			"m3atkn1ght",
	// 			"Rare_frog",
	// 			"jordanspiteri",
	// 			"MrBobQK",
	// 			"Tac0Tim3",
	// 			"AddictedGamer817",
	// 			"al10000",
	// 			"ButteryCream",
	// 			"kiryukazum",
	// 			"catsimpact08",
	// 			"attc",
	// 			"Meesz",
	// 			"File",
	// 			"Racejet",
	// 			"YayaJunOO",
	// 			"mqxxd",
	// 			"arranblue"
	// 		]
	// 	},
	// 	"WC31": {
	// 		"firstSeen": 1713043485829,
	// 		"players": [
	// 			"poopoolagoon",
	// 			"GottaGoFatteh",
	// 			"ChanceOfWin",
	// 			"crazydeadpool247",
	// 			"rrjol1209",
	// 			"Breezywilliams0",
	// 			"_Reimos",
	// 			"TheV3ntu5",
	// 			"TNTBumblebee",
	// 			"_Snowy_0y",
	// 			"Hitonano18",
	// 			"PinkShaze",
	// 			"98ml",
	// 			"TeTe8y",
	// 			"Trakoriis",
	// 			"LawnMower999",
	// 			"Aquatn",
	// 			"Rabbit_flower",
	// 			"NitrousSilver",
	// 			"iampro14",
	// 			"hahaTravel",
	// 			"buckasaurousrex",
	// 			"CuriousKaze",
	// 			"IQ5_No_Otoko",
	// 			"TheDogalaxy"
	// 		]
	// 	},
	// 	"WC2": {
	// 		"firstSeen": 1713040372211,
	// 		"players": [
	// 			"Wiscat17",
	// 			"iylx",
	// 			"AlphaT3ch",
	// 			"Soul_Retriever",
	// 			"TTYEET4912",
	// 			"SecretID_",
	// 			"skellington12",
	// 			"MiqoT",
	// 			"164ovo",
	// 			"eliix_x",
	// 			"FelineKarma85_jp",
	// 			"XylemPalce",
	// 			"CreatorGator",
	// 			"thecanfer",
	// 			"kkuuyyiinn",
	// 			"Shadow_Katt",
	// 			"Alpyg",
	// 			"J1_jp",
	// 			"nishaku200",
	// 			"SuperCheesyGamin",
	// 			"Suiseich",
	// 			"kuni_7",
	// 			"Orb1t18",
	// 			"VivioliRavioli"
	// 		]
	// 	},
	// 	"WC40": {
	// 		"firstSeen": 1713034967557,
	// 		"players": [
	// 			"Arch_N0ob_mAstr",
	// 			"hlickyalf",
	// 			"SkinnyAsianBoy",
	// 			"Obstacles_",
	// 			"Illumizeira",
	// 			"meowmeomeowmew",
	// 			"xruiva",
	// 			"Rustivard",
	// 			"Cymmerii",
	// 			"SovCunha",
	// 			"JvstMango",
	// 			"aeraLI",
	// 			"Konenala21",
	// 			"Knightslayer105",
	// 			"AzzyBee",
	// 			"Azift",
	// 			"Starkinho",
	// 			"errorpotato404",
	// 			"Xu_Feng_xdn",
	// 			"TheGoldenHusky",
	// 			"ozouni2485",
	// 			"Bagel360",
	// 			"aetriku",
	// 			"Pight_"
	// 		]
	// 	},
	// 	"WC7": {
	// 		"firstSeen": 1713036613910,
	// 		"players": [
	// 			"FnrEnder",
	// 			"CookiChan",
	// 			"MGamer404",
	// 			"MeoVT",
	// 			"KayKayST",
	// 			"Jrmble",
	// 			"trickyanthony",
	// 			"Al_Shehhi",
	// 			"ereMMVII",
	// 			"Vexorphius",
	// 			"Negitive_545",
	// 			"Keskaflow",
	// 			"rhinonick",
	// 			"ganadorph1",
	// 			"Budd3r4dawin",
	// 			"heyventix",
	// 			"WIZander",
	// 			"AngelFxre",
	// 			"biography",
	// 			"lucy8228",
	// 			"CrusadeSchools"
	// 		]
	// 	},
	// 	"WC23": {
	// 		"firstSeen": 1713037487033,
	// 		"players": [
	// 			"atawarudeath",
	// 			"ree8134515",
	// 			"TheGuardian693",
	// 			"Black_holy",
	// 			"Pokecrafter1204",
	// 			"minimaster419",
	// 			"WIllFandofer",
	// 			"7achyon",
	// 			"SweetCheeks_",
	// 			"yazeedissleepy",
	// 			"Dominox3",
	// 			"Shiny12",
	// 			"PomfPomfKimochi",
	// 			"keallor",
	// 			"ballchinianSc",
	// 			"MP3PLAY",
	// 			"masCreature",
	// 			"_Sault_",
	// 			"Plachez",
	// 			"BlueCorundum",
	// 			"immortalartisan",
	// 			"Dragostormer",
	// 			"TSBlader"
	// 		]
	// 	},
	// 	"WC6": {
	// 		"firstSeen": 1713040992999,
	// 		"players": [
	// 			"izzy4234",
	// 			"JMarsson28",
	// 			"linnyflower",
	// 			"dpsKokomi",
	// 			"YotamiDW",
	// 			"Kyian1225",
	// 			"Boltified",
	// 			"ppfart",
	// 			"Celesty0",
	// 			"Lallabella",
	// 			"Shireee",
	// 			"Anan5451",
	// 			"atchziens",
	// 			"Dannyxv8",
	// 			"bubblyAnime",
	// 			"FuhQx",
	// 			"Ekco",
	// 			"salyoutations",
	// 			"BlockBusss",
	// 			"Nynnf",
	// 			"Camden",
	// 			"Saphyris",
	// 			"iitzz_Dark",
	// 			"_Pain_Less_",
	// 			"AtomUnKnown",
	// 			"Felixstew",
	// 			"Pajama_Day",
	// 			"SilverSCore",
	// 			"Tom_Record",
	// 			"elroketson",
	// 			"TheRealTyco",
	// 			"EliteDuelist",
	// 			"1nfinity_",
	// 			"JKLDragon",
	// 			"BadNewsBears",
	// 			"Ayreseraph",
	// 			"YOUBETERUN",
	// 			"heart6008"
	// 		]
	// 	},
	// 	"WC29": {
	// 		"firstSeen": 1713060654853,
	// 		"players": [
	// 			"FireFly833",
	// 			"MissMeowMeowKat",
	// 			"IghorSantos",
	// 			"Pyrophany",
	// 			"Panadian",
	// 			"Jusslmao",
	// 			"EveofMadness",
	// 			"livlivlivia",
	// 			"LunarPixelOne",
	// 			"zhuzhuOwO",
	// 			"Crussant",
	// 			"Legomyeggominer",
	// 			"DankWetworkX",
	// 			"Joran_1337",
	// 			"ggonthemic",
	// 			"Wolfy5life",
	// 			"Emeraldsdsdsd",
	// 			"Jonathan45678",
	// 			"Kuro0929",
	// 			"Fatals_",
	// 			"WalnutChunk6181",
	// 			"meefy_",
	// 			"hackblackakm",
	// 			"CUjico",
	// 			"Zaynte",
	// 			"ArtistryMachine",
	// 			"buntails",
	// 			"rizi04b",
	// 			"thegekka",
	// 			"Arkarium",
	// 			"Mxxses",
	// 			"roKotine",
	// 			"ItsCatLmao",
	// 			"CorruptedLily"
	// 		]
	// 	},
	// 	"WC13": {
	// 		"firstSeen": 1713010628615,
	// 		"players": [
	// 			"KingLeonBrave",
	// 			"DinnerFast",
	// 			"ggsuru99",
	// 			"Inferiordude97",
	// 			"Lettereeno",
	// 			"CMPro",
	// 			"Trashed_Dumpster",
	// 			"Wystana",
	// 			"kirzem",
	// 			"MuchAwesomeboii",
	// 			"Hamster_God123",
	// 			"TheChancellor",
	// 			"Bubbalicious08",
	// 			"ReaperxArrow",
	// 			"vicodinL9",
	// 			"CyclopsMan0926",
	// 			"slashbin",
	// 			"planner1",
	// 			"jwtbh",
	// 			"Ipnotizzatore",
	// 			"BirchStarr",
	// 			"Magic_Avocado",
	// 			"Biam",
	// 			"Shear",
	// 			"Greundgul",
	// 			"LazyDergenBoi",
	// 			"Corbit",
	// 			"BirdyBlaze"
	// 		]
	// 	},
	// 	"WC39": {
	// 		"firstSeen": 1713031240687,
	// 		"players": [
	// 			"Reformed_Panda",
	// 			"Dominances",
	// 			"Ryzen239",
	// 			"Averted2",
	// 			"Cyro_gamez",
	// 			"Mrpicklesworth85",
	// 			"HeyGoat",
	// 			"xiaowu_666",
	// 			"LeafSaturation",
	// 			"LittleLapine",
	// 			"Hitmonlee",
	// 			"hcelestee",
	// 			"Camillerir",
	// 			"The_Toasticorn"
	// 		]
	// 	},
	// 	"WC8": {
	// 		"firstSeen": 1713041179752,
	// 		"players": [
	// 			"Kensu_Sama",
	// 			"ahrylai_03",
	// 			"Youngjuice2",
	// 			"dragonslash123",
	// 			"Draggon_Roll",
	// 			"Ragnarok11",
	// 			"Biblonko",
	// 			"6ec",
	// 			"AmazingMina",
	// 			"Boltoi",
	// 			"FinnckMalos",
	// 			"itizyou",
	// 			"_runaan",
	// 			"LososCroissant",
	// 			"EagleMNF",
	// 			"monkeybug34",
	// 			"danieltlq",
	// 			"cup1927",
	// 			"Artmis_Night",
	// 			"Macaroni2550",
	// 			"_XRN_",
	// 			"Hallucinations13",
	// 			"Ugastag",
	// 			"Vicano"
	// 		]
	// 	}
	// })
	const worldsData = {
		"WC38": {
			"firstSeen": 1713062705563,
			"players": [
				"Coolkid1206",
				"RevolvingOcelot",
				"Simpmulation",
				"ZipperDeer",
				"Vulpix1",
				"ReisBlau",
				"danot",
				"KodaAndKeyno",
				"hunter2776",
				"Stunbud",
				"InkedSk8ter",
				"nChaine",
				"MrQBurt",
				"TFoxy13",
				"TheLordXerxes",
				"takayama_bros",
				"FelixTape",
				"yotaaaaa",
				"Humongoustea178",
				"Drawss",
				"Bas_Tech",
				"tararaco",
				"FluffyPixel9",
				"Fanxiang",
				"JustJeffery",
				"Ed3l",
				"swimwater",
				"LionKing421",
				"Lemonsan666",
				"0MNlV0RE",
				"Syfilen"
			]
		},
		"WC43": {
			"firstSeen": 1713061711279,
			"players": [
				"Gamerboy1322020",
				"DuskyDusky",
				"KMsan",
				"Crimsondevilsin",
				"catg1rl",
				"Luna__Prism",
				"Henry_814",
				"ThatFortniteGuy",
				"Oldfox39",
				"PKfreeze123",
				"readly44",
				"SaffronCSF",
				"N0tChris",
				"dizaster6th",
				"Its_Meh",
				"Chambers02",
				"diamond_slayer5",
				"Prowombat3",
				"TheBryard",
				"brqndonn",
				"punscake",
				"Frozzx3102",
				"NokaHoa",
				"StayALIV3",
				"hoMiroNg",
				"Woealer",
				"Cruuk",
				"cluster_amarylli",
				"CrescentedFish",
				"IcarusDies",
				"Lucid_Hope",
				"muzf"
			]
		},
		"WC42": {
			"firstSeen": 1713063076995,
			"players": [
				"cerealki11ing",
				"koiifish_",
				"sharpieaddictt",
				"goombas_killer",
				"Le_Patito",
				"lopro2010",
				"XXMVNM123",
				"Meniscussssss",
				"Griimmmm",
				"ScytheOfLife",
				"Artificed",
				"_Commander_Ike_",
				"theSparkalina",
				"pugman421",
				"BoyofLength",
				"cam06060",
				"Debauche",
				"brilliantknight",
				"Princ3Victor",
				"Solublee",
				"yoshro27",
				"gobert_rl",
				"FireBlux3",
				"azhuuk",
				"TastyJason",
				"Taiwan_is_first",
				"monkeysorcerer2",
				"yayo2016",
				"FluffyCape87348",
				"13Amicus",
				"Lrum"
			]
		},
		"WC10": {
			"firstSeen": 1713046407836,
			"players": [
				"migu31",
				"Rd_Ctrlr",
				"ZaiSama_",
				"JimbiFist",
				"isakax",
				"_sni7ch",
				"MaxTm8",
				"ThDestr",
				"Peytondude8",
				"Doge4517",
				"zMars",
				"ningbun",
				"mosquitokill",
				"Aggusteen",
				"RipleyTheAxolotl",
				"nerdynerdz",
				"Lastly",
				"Cajahope",
				"MasterKaboom",
				"UnluckyPill",
				"Necryo_",
				"dollbite",
				"UnVanilla",
				"aqua0763",
				"EchoingGryffin",
				"xTheRedx",
				"jorge_ivan123",
				"vasectomylover2",
				"BakaUnicorn14",
				"IsseiHDxD",
				"Thira8",
				"_Toos_",
				"oseyuki",
				"Orphion_"
			]
		},
		"WC1": {
			"firstSeen": 1713041989209,
			"players": [
				"kitsunyaaaa",
				"igambleinchat",
				"Pokiie",
				"PIXEL_POSTER",
				"MrJulianB0T",
				"oKlaws_",
				"Aovhii",
				"ablockofdort",
				"Owieczka15",
				"OppositeMirror",
				"Error_402",
				"Aureuix",
				"5ura",
				"PlasmaWarrior",
				"PaisleyBiscuit",
				"TrNyxo",
				"BatClub",
				"leonatcam",
				"MCPro_Gamer",
				"Irredescent",
				"Forever_Night1",
				"IFionnaI_",
				"beurfus",
				"Manoogi",
				"2000IQ",
				"NeverForgetten",
				"Fishbasket74",
				"JldwL",
				"wilsan3",
				"jacobwfvp1",
				"G0ldenR0uoxls"
			]
		},
		"WC17": {
			"firstSeen": 1713048430984,
			"players": [
				11721172,
				"LordGonner",
				"Dorian_Marwood",
				"_B3N450_",
				"OmegaInbound",
				"nickbraves1",
				"twining_t86",
				"WoodHolland",
				"NasaNerd314",
				"AkuroR7",
				"DT_TKmVN",
				"DT_Gura",
				"Keqqu",
				"WoodKast",
				"DestroyManIV",
				"vrodih",
				"WoodVA",
				"ThaWood",
				"Incarceon_",
				"WoodLost",
				"Gombreng",
				"WoodCreature",
				"Jopher11733",
				"SrReikuz",
				"OmTaoEinsofManus",
				"LaDvdCorzo",
				"DT_Jack",
				"WoodXP",
				"PingouinDLS",
				"SentryPickle",
				"Voidarcher72",
				"Cucho2910"
			]
		},
		"WC27": {
			"firstSeen": 1713059876644,
			"players": [
				"DanOldMan",
				"Nomadixc",
				"succbucket",
				"meltingiam",
				"ReeceReineke",
				"Rade_emear",
				"VetroFPS",
				"FlowerPrincess",
				"GerberaSymphony",
				"Patro633",
				"ScalesInSweaters",
				"KN1GHTFALL",
				"white_boy",
				"CosmobbleSys",
				"RAYAXY",
				"oHate",
				"VolkyPolky",
				"BlakeDwarf",
				"Nnama",
				"IsaacDelta",
				"FoxShr00m",
				"feiPC123",
				"Drbiznes",
				"Baj_Baj",
				"HiSlIgHt_",
				"kristyboo",
				"meemmeem1",
				"oGeoff",
				"icehawk54",
				"Montews"
			]
		},
		"WC36": {
			"firstSeen": 1713030334852,
			"players": [
				"Yoonami",
				"FireRex206966",
				"Bosukude4649",
				"Xzazel",
				"Ewen_Le_Nain",
				"egg4059",
				"Nines_Own_Goal",
				"WhiteNoise0113",
				"EririLovegold",
				"H4iKiri",
				"HaNdY__",
				"YufanC",
				"itsdannyright"
			]
		},
		"WC21": {
			"firstSeen": 1713050547196,
			"players": [
				"LeLazi",
				"Masojia_jp",
				"Mihaukse",
				"facelessgoat11",
				"Dwaam",
				"heiru6199",
				"FluffySeal2988",
				"PengosPongos",
				"Univerouse",
				"ihyukai",
				"UhSnap",
				"lil_headass",
				"C4MERONXOX",
				"_topaz",
				"Spenchilada",
				"Enick",
				"DanOninho_",
				"PerUnknown",
				"Calluum",
				"aDri9101",
				"NKiritoN",
				"King__Bob",
				"IEA1000",
				"Ethos999",
				"adri88g",
				"CatPlayingGames",
				"BluBlueJay"
			]
		},
		"WC28": {
			"firstSeen": 1713037547549,
			"players": [
				"ObxM",
				"Temtem_TS",
				"Sumaho1008",
				"DragxD",
				"BuffJadeMining",
				"Toasty_boi",
				"Eshreal",
				"Stil_",
				"pugacy",
				"Ruekimou",
				"NotsoDumb",
				"SP1_Dragon",
				"Whath",
				"Doggc",
				"Cal_and_Ben",
				"GooseCore",
				"Sand_V3",
				"TKW256",
				"xSuzu",
				"SilverlyNight",
				"_Thinking_Face_",
				"Blademaster0",
				"Jasonplayzz",
				"TheNelston",
				"kubawu_",
				"Oblong_Sushi",
				"allizhi"
			]
		},
		"WC18": {
			"firstSeen": 1713052317725,
			"players": [
				"IDontLikeToDie",
				"Shebn",
				"VaadVaati",
				"CitraSama",
				"Scarlet_to_dream",
				"YouAreRexist",
				"badsoup",
				"jaxonishere",
				"Son_Of_Walter",
				"minebrine10",
				"GudSpeling",
				"Black_Scorpion_",
				"Colinix",
				"Conan0LM",
				"angycathy",
				"yhtacygna",
				"crafttatsuya",
				"RanaKikker",
				"xyrily",
				"SleepyMistix",
				"fangtianxing",
				"Wynderia",
				"Zatch",
				"HRJDragon",
				"Felirya"
			]
		},
		"WC20": {
			"firstSeen": 1713045226538,
			"players": [
				"Super_Sharkie",
				"Mxxrm",
				"maikeru34",
				"lecie4",
				"KeyWe_87_island",
				"svinerus",
				"GaboMcGamer",
				"noateto1",
				"Jenica",
				"JessicaPink703",
				"AdmiralDaizin",
				"HimesakaLuna",
				"XeiroFlora",
				"Vzax",
				"jaygoddd",
				"Act1vateWindows",
				"takasin1",
				"NinjaChicken95",
				"FancyKiwi",
				"PartlySunny",
				"Gensubaru",
				"boyfrom",
				"mikeworld3",
				"R_Ruffles",
				"TinyRedRaceCar",
				"Oyasai_JE9100"
			]
		},
		"WC9": {
			"firstSeen": 1713037080442,
			"players": [
				"OrphanedChild",
				"PimpleDimps",
				"RTrinh563",
				"Ahuizotll",
				"RikuMochi",
				"Qu3st1on",
				"Ossydeussy",
				"t4be",
				"xXZaBriNgAXx",
				"zJury",
				"Cursed2w1",
				"Paradision",
				"sc2sr",
				"Housery",
				"RubMyMineshaft",
				"p_b_d_matcha8931",
				"DarkFeather556",
				"xAkumi",
				"SillyScrew",
				"Azomth",
				"yap_per",
				"jia_qin",
				"dog_eggs",
				"Lemon_Pan",
				"Mail_Watdaimod",
				"FabDoesStuff",
				"Nightslasher38",
				"kyeun",
				"AXYEHHOKPYTO",
				"whiteguy48"
			]
		},
		"WC37": {
			"firstSeen": 1713050861666,
			"players": [
				"tummblez99",
				"smaching",
				"Frogstand",
				"Techno_Guy_KWP",
				"Ruinc",
				"OverlordAlastor",
				"SkimBeebs",
				"WhiteFang__",
				"YOKOKUMA",
				"HeavyMetalHaven",
				"TacoCat7653",
				"ohitslemon",
				"TakiCesar",
				"BaggierTree3320",
				"WestCandle_JP",
				"wrubiix",
				"Johnadam211212",
				"Sub__Par",
				"kai_chen0602",
				"Zaidob",
				"UnusualHeron",
				"Fan2mario64",
				"BarGam1",
				"ryktcompassrose",
				"MaybeLatah",
				"TuLouis",
				"Puurpleman",
				"ElohmroW",
				"Cataath"
			]
		},
		"WC33": {
			"firstSeen": 1713036613770,
			"players": [
				"TheZe_",
				"IMagister",
				"The_Big_Bunga",
				"Mouseydavid10",
				"Tqkened",
				"LT_Universe",
				"thatFishStick",
				"ESTTGD",
				"TheCloakMan",
				"xx_bacon_man_xx",
				"Rojeel",
				"Iware_Pond",
				"POPOPIYA",
				"Mo1G4mez",
				"Overvolt1000",
				"SorrowfulLady",
				"Skorm_Axebreaker",
				"AWildHoshiyomi",
				"mahiro1219",
				"ProjectForceV2",
				"rynf",
				"ManMysterious",
				"Brutakah",
				"Red_Fox_Rogue",
				"Crescentmoon621",
				"falconthunder"
			]
		},
		"WC14": {
			"firstSeen": 1713059380165,
			"players": [
				"zeky",
				"NOOBYPANDA_",
				"Rahvin2007",
				"Acorn11",
				"Seraphim_Rayn",
				"EpicWynn",
				"Scarface_Connor",
				"Ehsbii",
				"Ulitiminer4172",
				"xRisePunch",
				"ekozi",
				"MidNightMisT880",
				"Nitroxlz",
				"Ratalistic",
				"Player6650",
				"SnowFox166",
				"EXARTIUS",
				"aronkodol",
				"Harm7",
				"FraekInMuscle",
				"Opmusic",
				"thefugitiveminer",
				"skyblueswordsman",
				"TaKarir",
				"nctrequiem",
				"__Tempestissimo",
				"RolleBolle55",
				"ParasiticHelmint",
				"Ventari_Wylde",
				"pockt"
			]
		},
		"WC35": {
			"firstSeen": 1713050607784,
			"players": [
				"FaintCalf59547",
				"DannyDanBoy",
				"MERO_02",
				"Blazedancer",
				"illuminus_metam",
				"sol798",
				"Awkweat",
				"SimplySlim3",
				"Doctor_Whooves42",
				"Jagaro",
				"Gravetide",
				"AnAceSpade",
				"KREJ10",
				"__bone__",
				"cobalt771",
				"jade_rabbit1124",
				"Re0_Rem",
				"ItsLionknight",
				"0O0X0O0",
				"McHimbo",
				"PK2006",
				"SassyGay",
				"SueDillon",
				"Chanwhun",
				"KaoDremora",
				"Smellbo_",
				"Nightfury13",
				"Jacobi102030",
				"Greenbracelet",
				"Volcanic_Gamer",
				"Domisboss2014"
			]
		},
		"WC15": {
			"firstSeen": 1713041863547,
			"players": [
				"CaptainG2280",
				"InozaAki_",
				"Axyrius",
				"Rita_87_island",
				"SuperSein",
				"Kneem",
				"bluemidsdog",
				"ABlack4",
				"AtrejuPlays",
				"driacore",
				"dDANTE_S",
				"Fleega",
				"AreFeetShoes",
				"TrissyTiger",
				"Ataraxyia",
				"KutekutoBonsai",
				"LilacMasquerade",
				"Arcellis",
				"Marstrosity",
				"TheMelonDragon",
				"ILikeU",
				"Murdery",
				"PhyzzyBop",
				"CrazyTiger12908",
				"sbellebound",
				"Mrblaze1301",
				"uruy"
			]
		},
		"WC12": {
			"firstSeen": 1713057949533,
			"players": [
				"Fanta_lemonPie",
				"Lord_Qwerty_Pyro",
				"AlistorTheWolf",
				"SpaceHusky17",
				"Dragon_slayer820",
				"sadgeleaf1",
				"Starsxul",
				"freeMCsmoke",
				"zman1der",
				"Chaioth_haQadesh",
				"killaang",
				"Vakama",
				"danscorruption",
				"x3n1",
				"juli793",
				"Jamal_meow",
				"SPAC3M0NK3Y",
				"Nekk0mancer",
				"2Hero",
				"wabey",
				"chickrame",
				"Drobicus",
				"MortalMaximus",
				"egyog",
				"tsumikijenga_234",
				"ChampionFighter",
				"Clezynemy123",
				"Dinhsiudeptrai",
				"Tacosoftware9000",
				"SinanBruh",
				"Drawwy"
			]
		},
		"WC22": {
			"firstSeen": 1713037953076,
			"players": [
				"Blankown",
				"vrdr",
				"Legolucas1472",
				"Fern_Ottors",
				"Testo_",
				"orangetofu",
				"Stavrozius7",
				"Lituk",
				"TheAnonymousRain",
				"daiebi14",
				"defnotlexi",
				"RazzorHDD",
				"origamiking152",
				"Jaggster",
				"Weedow_",
				"AutisticCrumbs",
				"Rye21",
				"sumituba4328",
				"JammiestDodger",
				"HX7D",
				"Docokarra",
				"oiSnow",
				"FuturePlantsTM",
				"Styx_He1ix",
				"IgnisDragon",
				"star473",
				"ToucanTimm",
				"omamesinzu",
				"IIlShadowII",
				"ItsJustKnoxx",
				"Charlieoffps",
				"catgirlviona",
				"Dorothy62",
				"Zerindal"
			]
		},
		"WC34": {
			"firstSeen": 1713042176818,
			"players": [
				"AndDrew_",
				"latryxx",
				"Duks",
				"Trodeno",
				"StealyOats",
				"GooseTen",
				"Capt_Fox241",
				"VoraOfficial",
				"Auri_El",
				"Hyacinth_Oppop",
				"GameHappy",
				"IDoBeSimpingTho",
				"odeska",
				"Reser2207",
				"bare__",
				"TheEaf",
				"FrostOffSum",
				"GluePowa",
				"Secret_FruityCat",
				"BreadBurglar",
				"inari080",
				"kn8900",
				"Poo_najak",
				"PaLiNoxSR",
				"CebuPacific",
				"RaccoonLover9000",
				"Monamiii",
				"Run_O101",
				"redpanda508"
			]
		},
		"WC3": {
			"firstSeen": 1713034563344,
			"players": [
				"Katalyst_x",
				"Mirvam",
				"Uoog",
				"YerMumsDad",
				"CrystalFlux",
				"funkylezzo",
				"SaibaKurokawa",
				"AsianCat",
				"gig4c4zo",
				"Strife_Cloud",
				"Forgetfulpass",
				"Creampuffboy",
				"MrGalacto",
				"Daimax_19",
				"Nooten_56",
				"Mickaelhz",
				"MoonAvem",
				"thenumberonedud",
				"Demonwes123",
				"bobarken",
				"Odogo",
				"Wasasi",
				"ixiclestinger22",
				"MicrosRevenge",
				"Hexodus",
				"Damakos3"
			]
		},
		"WC4": {
			"firstSeen": 1713055616365,
			"players": [
				"ukcat68",
				"MetalBox47",
				"Flydane",
				"morest",
				"tonyloco13",
				"JVRQ",
				"rinobo1122",
				"Super02starL",
				"atomilogical",
				"pnoot",
				"Heidychyyy",
				"MysticDireWolves",
				"ItsLeafeon55",
				"TheLukinator2022",
				"KatskaBee",
				"SarahLeSimp",
				"FrootyToots",
				"Xiissue",
				"Gurdus",
				"Doubletime_T",
				"BliTZed_PaNdA",
				"Mr_poopybutthole",
				"Sir_Aaronymus",
				"4nei",
				"SleepyT2883",
				"eatwithspork",
				"MR_catalot",
				"ImagineKami",
				"helow127",
				"Insighted",
				"Sosit4",
				"NinjaWasser",
				"IamTheDuke"
			]
		},
		"WC11": {
			"firstSeen": 1713043607682,
			"players": [
				"Bennykelli1",
				"Tis_awesomeness",
				"SnUg3d",
				"Wemydastore",
				"GoodmanPasta",
				"Whom_Asked",
				"InfernalIE",
				"derpsir",
				"StreekSeyt",
				"fj70",
				"RamSimp",
				"KSR2020",
				"xXPoppa_WoodyXx",
				"Dat808Taco",
				"_Karsalesman_",
				"Keldorn",
				"bapafish",
				"Tavahn",
				"Pokeguy946",
				"Beetown",
				"PhysCrenata",
				"HaiMast3r",
				"Youkan5101",
				"_greencat_",
				"Cammo_353",
				"CYR______",
				"OkCya",
				"ZennyTV",
				"nequil",
				"Hotdogchria"
			]
		},
		"WC44": {
			"firstSeen": 1713063327523,
			"players": [
				"Kayde_Official",
				"Evemy",
				"KZGtaye",
				"UwUGamer007",
				"DR_saltshaker",
				"EKOHC",
				"Stanley_Chen",
				"ImEcho_",
				"hahafunny37",
				"Gavroxx",
				"amun_rai",
				"stogy115",
				"potato_duck16",
				"SuperbotOX",
				"hakunagi314",
				"striqz",
				"GameKnightAndy",
				1110110101,
				"Icenka_Gamer",
				"snakebr0",
				"neversmoke",
				"skyrimfan1",
				"Ryo_tele2456",
				"kei_kou_",
				"_wuki_",
				"Danh_005",
				"junhang_lee1",
				"Rusty_Bubble",
				"Amitajun",
				"Xyruh"
			]
		},
		"WC26": {
			"firstSeen": 1713043172968,
			"players": [
				"bendstandingman",
				"tappy1045",
				"Pocabu",
				"ThomasTRO_",
				"StePlays",
				"elmost1",
				"ile123ile",
				"CodeJock42069",
				"d4ark4angel",
				"pentahedron",
				"__Minor__",
				"bobby686868",
				"skrybs",
				"Rowebbs",
				"Fqpq",
				"Az011",
				"flyingducks777",
				"Sea0tter_",
				"FungeonKeeper",
				"CoweCat",
				"geenee10",
				"LuxRow1",
				"Cameron62",
				"Luvln",
				"feruram",
				"Le_Boi123",
				"leakytoe"
			]
		},
		"WC32": {
			"firstSeen": 1713060870865,
			"players": [
				"Sykrvll",
				"Korinya",
				"KoalaPro07",
				"Sane_Tempest",
				"Nimble_Deer",
				"Zomadan",
				"PicklePiePro",
				"pengen1",
				"RedstoneProGamer",
				"MKnotJFK",
				"Ceobe_yyds",
				"Harmonance",
				"VolumRPG",
				"SnowTrunks",
				"SecretionThief",
				"Delicy18",
				"boniebel",
				"JellyByte",
				"RobSmurdaa",
				"Zeeye",
				"Happy_Dayo",
				"Kazemi_Ayaha",
				"nekoron5041",
				"CoopyTroopy21",
				"Sorukekorashoman",
				"Quiznq",
				"_thedealer_",
				"_f1Lthz4",
				"Redzel",
				"Frat_Boyz"
			]
		},
		"WC5": {
			"firstSeen": 1713044604600,
			"players": [
				"MrBozini",
				"soler3",
				"Pododeng",
				"i_am_farrah",
				"26mhu",
				"Shararamoshik",
				"U_matter",
				"DEAD_SHOT2011",
				"yot",
				"Didder_",
				"elighten",
				"Tunium",
				"Marius_Dao",
				"nuser3",
				"BongoBongoBongo",
				"PencilThief",
				"Lightning64",
				"Splash_Gradation",
				"Dy_",
				"FinnFindlay",
				"Linaxox",
				"fennectech",
				"Cqyle",
				"Zexoria",
				"brog_us",
				"Samredstone",
				"MinhtyTime",
				"SpinaRosam",
				"heodang12"
			]
		},
		"WC19": {
			"firstSeen": 1713060531138,
			"players": [
				"Nonchucks",
				"ToastAnimate",
				"DurJak",
				"ka121",
				"Astropeanutbuttr",
				"orangutan_poop",
				"Walkless",
				"Dude__Guy",
				"Diableg",
				"Setoka7",
				"AtlasOpus",
				"IgnitusDragon442",
				"Voramok573",
				"Abo7md_xpro",
				"JustTornado",
				"PlayerSlayer1998",
				"TimeValley",
				"CrustyGoatCheese",
				"AllGudNamesGone",
				"timeforfrog",
				"HakuKatla",
				"derpytron5000",
				"madzeN115",
				"Kenai77",
				"masaki0429",
				"puppah",
				"IncinerateMe",
				"_cool_steve_",
				"max267",
				"Person8790",
				"ImaJC",
				"DandiestTrack66",
				"cuteboy23456666",
				"UchiHahahaha",
				"kpolr",
				"Theyyk"
			]
		},
		"WC41": {
			"firstSeen": 1713044231922,
			"players": [
				"notazu",
				"Cledward",
				"jonjon286",
				"Rire3",
				"Ayayka",
				"49mg",
				"Rockargen",
				"cavera76",
				"Prongl",
				"ModeloDaLOreal",
				"rockbusterbg",
				"Salzmanderzz",
				"Doubledash08",
				"Luanex",
				"Snownlite",
				"HumanityOK",
				"juria0",
				"Gummybear1121",
				"GomjelliMakeutu",
				"RitualRaven",
				"LovelyMoca",
				"Turttlezs",
				"maeu_",
				"Umbraleviathan",
				"Froppii_",
				"Myunari",
				"Pdak",
				"_IlyCarrot",
				"4Kyro",
				"ToboCoolMan2000",
				"LordMeGusta",
				"Astere0n",
				"Noxer69"
			]
		},
		"WC24": {
			"firstSeen": 1713063202432,
			"players": [
				"MICHAELXHCA",
				"BitPlayer8147",
				"LookAtMe_XD",
				"TOOKEN_",
				"wiitard",
				"soileddirt",
				"warzone741",
				"qiushan1216",
				"OPTanksteel",
				"konhiro247",
				"KillaLalas",
				"Zaglington",
				"ReallyUncool",
				"DropIt",
				"3Pie",
				"_2u",
				"SilverWarSi",
				"cyberia99",
				"Bnnui",
				"Borzah",
				"NSL_Wryyyyy",
				"Deadpan43",
				"LastIsAFK",
				"Phinx",
				"Acid_07",
				"papurika1024",
				"WHAFFLEZ_",
				"Nyethal",
				"tatty5678",
				"LogicalHawk5"
			]
		},
		"WC30": {
			"firstSeen": 1713057076386,
			"players": [
				"BlackDarkness419",
				"reeefleks",
				"Arquerodark1",
				"isaaciscrying",
				"Glow_pup",
				"RemiaHippo",
				"orenge_",
				"BigCatRescue",
				"Albhis",
				"hnnl",
				"Pingu_7",
				"Gee_55",
				"k0_Fu",
				"coffincrow",
				"LionCrafter64",
				"KennvRave",
				"XXIcedxX",
				"Rurinkitoz",
				"01_",
				"DogeLife367",
				"convolvulus",
				"GabrielEF",
				"Bunnah",
				"PainlessStorage1",
				"MOMOneko7",
				"Kraetys",
				"OGC__",
				"MadLad63"
			]
		},
		"WC47": {
			"firstSeen": 1713038201970,
			"players": [
				"DevilPlays10",
				"DarkestKnight6",
				"GoneClassy",
				"Monkeykapaa",
				"Burnt_Toast68",
				"PastorRacoon",
				"Vxxed888",
				"Rapid22",
				"BumptyDumpty",
				"MomWood",
				"Skyrkazm",
				"earcra0106",
				"FizzyPlayz28",
				"Ca2lumG",
				"SunbreakTitan07",
				"Dragon4564",
				"grey833",
				"just_in_time87",
				"soymilkluce",
				"lilly_four",
				"ZmanMythhead",
				"yFelipeMC_",
				"KobaHemm",
				"maplu"
			]
		},
		"WC16": {
			"firstSeen": 1713042239314,
			"players": [
				"Lqna",
				"Toi1et",
				"Cylestialstar",
				"TravelerMerchant",
				"cjtrahan2005",
				"Giluzarku37427",
				"jiru6552",
				"crounon",
				"GrubbierAsp",
				"Nooby13",
				"Kirby219",
				"Antonemy",
				"Jbote87",
				"RadiantZelda",
				"m3atkn1ght",
				"Rare_frog",
				"jordanspiteri",
				"MrBobQK",
				"Tac0Tim3",
				"AddictedGamer817",
				"al10000",
				"ButteryCream",
				"kiryukazum",
				"catsimpact08",
				"attc",
				"Meesz",
				"File",
				"Racejet",
				"YayaJunOO",
				"mqxxd",
				"arranblue"
			]
		},
		"WC31": {
			"firstSeen": 1713043485829,
			"players": [
				"poopoolagoon",
				"GottaGoFatteh",
				"ChanceOfWin",
				"crazydeadpool247",
				"rrjol1209",
				"Breezywilliams0",
				"_Reimos",
				"TheV3ntu5",
				"TNTBumblebee",
				"_Snowy_0y",
				"Hitonano18",
				"PinkShaze",
				"98ml",
				"TeTe8y",
				"Trakoriis",
				"LawnMower999",
				"Aquatn",
				"Rabbit_flower",
				"NitrousSilver",
				"iampro14",
				"hahaTravel",
				"buckasaurousrex",
				"CuriousKaze",
				"IQ5_No_Otoko",
				"TheDogalaxy"
			]
		},
		"WC2": {
			"firstSeen": 1713040372211,
			"players": [
				"Wiscat17",
				"iylx",
				"AlphaT3ch",
				"Soul_Retriever",
				"TTYEET4912",
				"SecretID_",
				"skellington12",
				"MiqoT",
				"164ovo",
				"eliix_x",
				"FelineKarma85_jp",
				"XylemPalce",
				"CreatorGator",
				"thecanfer",
				"kkuuyyiinn",
				"Shadow_Katt",
				"Alpyg",
				"J1_jp",
				"nishaku200",
				"SuperCheesyGamin",
				"Suiseich",
				"kuni_7",
				"Orb1t18",
				"VivioliRavioli"
			]
		},
		"WC40": {
			"firstSeen": 1713034967557,
			"players": [
				"Arch_N0ob_mAstr",
				"hlickyalf",
				"SkinnyAsianBoy",
				"Obstacles_",
				"Illumizeira",
				"meowmeomeowmew",
				"xruiva",
				"Rustivard",
				"Cymmerii",
				"SovCunha",
				"JvstMango",
				"aeraLI",
				"Konenala21",
				"Knightslayer105",
				"AzzyBee",
				"Azift",
				"Starkinho",
				"errorpotato404",
				"Xu_Feng_xdn",
				"TheGoldenHusky",
				"ozouni2485",
				"Bagel360",
				"aetriku",
				"Pight_"
			]
		},
		"WC7": {
			"firstSeen": 1713036613910,
			"players": [
				"FnrEnder",
				"CookiChan",
				"MGamer404",
				"MeoVT",
				"KayKayST",
				"Jrmble",
				"trickyanthony",
				"Al_Shehhi",
				"ereMMVII",
				"Vexorphius",
				"Negitive_545",
				"Keskaflow",
				"rhinonick",
				"ganadorph1",
				"Budd3r4dawin",
				"heyventix",
				"WIZander",
				"AngelFxre",
				"biography",
				"lucy8228",
				"CrusadeSchools"
			]
		},
		"WC23": {
			"firstSeen": 1713037487033,
			"players": [
				"atawarudeath",
				"ree8134515",
				"TheGuardian693",
				"Black_holy",
				"Pokecrafter1204",
				"minimaster419",
				"WIllFandofer",
				"7achyon",
				"SweetCheeks_",
				"yazeedissleepy",
				"Dominox3",
				"Shiny12",
				"PomfPomfKimochi",
				"keallor",
				"ballchinianSc",
				"MP3PLAY",
				"masCreature",
				"_Sault_",
				"Plachez",
				"BlueCorundum",
				"immortalartisan",
				"Dragostormer",
				"TSBlader"
			]
		},
		"WC6": {
			"firstSeen": 1713040992999,
			"players": [
				"izzy4234",
				"JMarsson28",
				"linnyflower",
				"dpsKokomi",
				"YotamiDW",
				"Kyian1225",
				"Boltified",
				"ppfart",
				"Celesty0",
				"Lallabella",
				"Shireee",
				"Anan5451",
				"atchziens",
				"Dannyxv8",
				"bubblyAnime",
				"FuhQx",
				"Ekco",
				"salyoutations",
				"BlockBusss",
				"Nynnf",
				"Camden",
				"Saphyris",
				"iitzz_Dark",
				"_Pain_Less_",
				"AtomUnKnown",
				"Felixstew",
				"Pajama_Day",
				"SilverSCore",
				"Tom_Record",
				"elroketson",
				"TheRealTyco",
				"EliteDuelist",
				"1nfinity_",
				"JKLDragon",
				"BadNewsBears",
				"Ayreseraph",
				"YOUBETERUN",
				"heart6008"
			]
		},
		"WC29": {
			"firstSeen": 1713060654853,
			"players": [
				"FireFly833",
				"MissMeowMeowKat",
				"IghorSantos",
				"Pyrophany",
				"Panadian",
				"Jusslmao",
				"EveofMadness",
				"livlivlivia",
				"LunarPixelOne",
				"zhuzhuOwO",
				"Crussant",
				"Legomyeggominer",
				"DankWetworkX",
				"Joran_1337",
				"ggonthemic",
				"Wolfy5life",
				"Emeraldsdsdsd",
				"Jonathan45678",
				"Kuro0929",
				"Fatals_",
				"WalnutChunk6181",
				"meefy_",
				"hackblackakm",
				"CUjico",
				"Zaynte",
				"ArtistryMachine",
				"buntails",
				"rizi04b",
				"thegekka",
				"Arkarium",
				"Mxxses",
				"roKotine",
				"ItsCatLmao",
				"CorruptedLily"
			]
		},
		"WC13": {
			"firstSeen": 1713010628615,
			"players": [
				"KingLeonBrave",
				"DinnerFast",
				"ggsuru99",
				"Inferiordude97",
				"Lettereeno",
				"CMPro",
				"Trashed_Dumpster",
				"Wystana",
				"kirzem",
				"MuchAwesomeboii",
				"Hamster_God123",
				"TheChancellor",
				"Bubbalicious08",
				"ReaperxArrow",
				"vicodinL9",
				"CyclopsMan0926",
				"slashbin",
				"planner1",
				"jwtbh",
				"Ipnotizzatore",
				"BirchStarr",
				"Magic_Avocado",
				"Biam",
				"Shear",
				"Greundgul",
				"LazyDergenBoi",
				"Corbit",
				"BirdyBlaze"
			]
		},
		"WC39": {
			"firstSeen": 1713031240687,
			"players": [
				"Reformed_Panda",
				"Dominances",
				"Ryzen239",
				"Averted2",
				"Cyro_gamez",
				"Mrpicklesworth85",
				"HeyGoat",
				"xiaowu_666",
				"LeafSaturation",
				"LittleLapine",
				"Hitmonlee",
				"hcelestee",
				"Camillerir",
				"The_Toasticorn"
			]
		},
		"WC8": {
			"firstSeen": 1713041179752,
			"players": [
				"Kensu_Sama",
				"ahrylai_03",
				"Youngjuice2",
				"dragonslash123",
				"Draggon_Roll",
				"Ragnarok11",
				"Biblonko",
				"6ec",
				"AmazingMina",
				"Boltoi",
				"FinnckMalos",
				"itizyou",
				"_runaan",
				"LososCroissant",
				"EagleMNF",
				"monkeybug34",
				"danieltlq",
				"cup1927",
				"Artmis_Night",
				"Macaroni2550",
				"_XRN_",
				"Hallucinations13",
				"Ugastag",
				"Vicano"
			]
		}
	}

	const [worlds, setWorlds] = useState(null)




	// const [worlds, setWorlds] = useState(null)

	function msToTimeLeft(duration) {
        let seconds = Math.floor((duration / 1000) % 60)
        let minutes = Math.floor((duration / (1000 * 60)) % 60)

        minutes = 19 - (minutes % 20)
        seconds = seconds !== 0 ? 60 - seconds : seconds


        // minutes = (minutes < 10) ? "0" + minutes : minutes
        // seconds = (seconds < 10) ? "0" + seconds : seconds

        return (minutes * 60) + seconds
    }

	useEffect(() => {
		// let arr = [...Object.entries(worlds)]
		let sorted = [...Object.entries(worldsData)].sort(function (a, b) {
			let keyA = new Date(msToTimeLeft(a[1]['firstSeen']))
			let keyB = new Date(msToTimeLeft(b[1]['firstSeen']))
			
			if (keyA < keyB) return -1
			if (keyA > keyB) return 1
			
			return 0
		});

		
		console.log(sorted)

		setWorlds(sorted)
		// console.log(sorted)
		// axios.get('https://athena.wynntils.com/cache/get/serverList')
		// axios.get('https://random-word-api.herokuapp.com/word')
		// .then(res => {
			// console.log(res.data)
			// setWorlds(res.data)
		// })
		// console.log(worlds)
	}, [])

	return (
		<div className='bg-zinc-950 min-h-screen text-white px-10'>
			<Hero />
			<span className='block w-2/5 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent m-auto' />
			<section className='flex flex-col gap-2 items-center col-span-2 max-w-3xl mx-auto py-4 md:py-10'>
				{!worlds ? (
					<>
						<p className='text-red-400 font-bold animate-pulse'>This Can Take Up To 1 Minute To Load</p>
						{[...Array(10)].map(e =>
							<span className='w-full sm:h-12 h-16 bg-zinc-900 rounded-sm flex sm:flex-row flex-col sm:justify-between justify-center items-center px-4 hover:bg-zinc-800 duration-150 shadow-md animate-pulse'>
								<div>World: ...</div>
								<div>Next SP: ...</div>
							</span>
						)}
					</>
				) : (
					worlds.map((e, i) =>
						<World key={i} name={e[0]} players={e[1]['players']} time={e[1]['firstSeen']} other={msToTimeLeft(e[1]['firstSeen'])} />
					)
				)}
			</section>
			<span className='block w-2/5 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent m-auto' />
		</div>
	);
}

export default App;
